import {
  Sun,
  CloudRain,
  Cloud,
  Wind,
  Moon,
  CloudSun,
  Flame,
  CloudLightning,
  Circle,
  Waves,
  CloudSnow,
  CloudFog,
  Factory,
  Droplets,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';
import type { WeatherType } from '@/types/shared.types';

/**
 *
 */
export interface WeatherConfig {
  icon: LucideIcon;
  colorClass: string;
  bgClass: string;
  borderClass: string;
  extraClass?: string;
  description: string;
}

export const WEATHER_CONFIG: Record<WeatherType, WeatherConfig> = {
  'Prismatic Rain': {
    icon: Sparkles,
    colorClass: 'text-primary',
    bgClass: 'bg-primary/10',
    borderClass: 'border-primary/20',
    description: 'Iridescent rain falls, strangely energizing the fighters. 15% more stamina drain in combat.',
  },
  'Eldritch Eclipse': {
    icon: Moon,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    extraClass: 'glow-neon-purple',
    description: 'An otherworldly eclipse that drives fighters to the brink of madness.',
  },
  'Moonlight Duel': {
    icon: Moon,
    colorClass: 'text-arena-pop',
    bgClass: 'bg-arena-pop/10',
    borderClass: 'border-arena-pop/20',
    description: 'A secret midnight challenge. 10% more stamina drain in combat.',
  },

  Zephyr: {
    icon: Wind,
    colorClass: 'text-primary',
    bgClass: 'bg-primary/10',
    borderClass: 'border-primary/20',
    description: '15% less stamina drain in combat. Fighters feel refreshed.',
  },
  'Wild Magic': {
    icon: Sparkles,
    colorClass: 'text-arena-pop',
    bgClass: 'bg-arena-pop/10',
    borderClass: 'border-arena-pop/20',
    description: '10% more damage across the board due to wild magic.',
  },
  Clear: {
    icon: Sun,
    colorClass: 'text-arena-gold',
    bgClass: 'bg-arena-gold/10',
    borderClass: 'border-arena-gold/20',
    description: 'Standard atmospheric conditions.',
  },
  'Crimson Snow': {
    icon: CloudSnow,
    colorClass: 'text-destructive',
    bgClass: 'bg-destructive/10',
    borderClass: 'border-destructive/20',
    description: 'Red snow numbs the limbs and increases bloodthirst.',
  },
  Rainy: {
    icon: CloudRain,
    colorClass: 'text-muted-foreground',
    bgClass: 'bg-muted/10',
    borderClass: 'border-muted/20',
    description: 'Poor visibility and slick ground penalize initiative and attack.',
  },
  Overcast: {
    icon: CloudSun,
    colorClass: 'text-arena-steel',
    bgClass: 'bg-arena-steel/10',
    borderClass: 'border-arena-steel/20',
    description: 'Standard atmospheric conditions.',
  },
  Sweltering: {
    icon: Flame,
    colorClass: 'text-arena-blood',
    bgClass: 'bg-arena-blood/10',
    borderClass: 'border-arena-blood/20',
    description: '30% more stamina drain in combat.',
  },
  Breezy: {
    icon: Wind,
    colorClass: 'text-stone-300',
    bgClass: 'bg-stone-300/10',
    borderClass: 'border-stone-300/20',
    description: '10% less stamina drain in combat.',
  },
  'Blazing Sun': {
    icon: Sun,
    colorClass: 'text-destructive',
    bgClass: 'bg-destructive/10',
    borderClass: 'border-destructive/20',
    description: '40% more stamina drain in combat.',
  },
  Gale: {
    icon: CloudLightning,
    colorClass: 'text-arena-pop',
    bgClass: 'bg-arena-pop/10',
    borderClass: 'border-arena-pop/20',
    description: 'Fierce winds. 20% more stamina drain in combat.',
  },
  'Blood Moon': {
    icon: Moon,
    colorClass: 'text-destructive',
    bgClass: 'bg-destructive/10',
    borderClass: 'border-destructive/20',
    description: 'A crimson moon rises. Fighters are bloodthirsty, vastly increasing lethality.',
  },
  Eclipse: {
    icon: Circle,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    description: '20% less stamina drain in combat. Fights are slow and methodical.',
  },
  Sandstorm: {
    icon: Waves,
    colorClass: 'text-arena-gold',
    bgClass: 'bg-arena-gold/10',
    borderClass: 'border-arena-gold/20',
    description: 'Choking dust drains stamina and blinds fighters.',
  },
  Mist: {
    icon: Cloud,
    colorClass: 'text-stone-300',
    bgClass: 'bg-stone-300/10',
    borderClass: 'border-stone-300/20',
    description: 'Reduced visibility makes initial strikes trickier.',
  },
  'Glittering Frost': {
    icon: CloudSnow,
    colorClass: 'text-arena-steel',
    bgClass: 'bg-arena-steel/10',
    borderClass: 'border-arena-steel/20',
    description: 'Sharp frost increases damage but bites the lungs.',
  },
  'Scorching Wind': {
    icon: Wind,
    colorClass: 'text-destructive',
    bgClass: 'bg-destructive/10',
    borderClass: 'border-destructive/20',
    description: '30% more stamina drain in combat. Fighters push harder and act rashly.',
  },
  'Spooky Night': {
    icon: Moon,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    extraClass: 'glow-neon-purple',
    description: 'An unnatural chill and eerie shadows make fighters nervous and jumpy.',
  },
  Blizzard: {
    icon: CloudSnow,
    colorClass: 'text-arena-pop',
    bgClass: 'bg-arena-pop/10',
    borderClass: 'border-arena-pop/20',
    description: 'Freezing conditions. 50% more stamina drain in combat.',
  },
  'Dense Fog': {
    icon: CloudFog,
    colorClass: 'text-arena-steel',
    bgClass: 'bg-arena-steel/10',
    borderClass: 'border-arena-steel/20',
    description: 'Reduced visibility makes initial strikes trickier.',
  },
  Thunderstorm: {
    icon: CloudLightning,
    colorClass: 'text-arena-gold',
    bgClass: 'bg-arena-gold/10',
    borderClass: 'border-arena-gold/20',
    description: 'Electrical storms. 20% more stamina drain in combat.',
  },
  Ashfall: {
    icon: Factory,
    colorClass: 'text-muted-foreground',
    bgClass: 'bg-muted/10',
    borderClass: 'border-border/40',
    description: 'Volcanic ash reduces visibility and irritates eyes.',
  },
  'Acid Rain': {
    icon: Droplets,
    colorClass: 'text-arena-gold',
    bgClass: 'bg-arena-gold/10',
    borderClass: 'border-arena-gold/20',
    description: 'Corrosive rain damages equipment and increases injury risk.',
  },
  'Mana Surge': {
    icon: Sparkles,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    description: 'Magical energy surges through the arena, enhancing special abilities.',
  },
  'Astral Dust': {
    icon: Sparkles,
    colorClass: 'text-primary',
    bgClass: 'bg-primary/10',
    borderClass: 'border-primary/20',
    description: 'Shimmering star dust makes movements erratic and draining.',
  },
  'Aurora Borealis': {
    icon: Sparkles,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    description: 'The sky dances with spectral light. Fighters feel a strange, invigorating calm.',
  },
  'Aether Storm': {
    icon: Sparkles,
    colorClass: 'text-arena-gold',
    bgClass: 'bg-arena-gold/10',
    borderClass: 'border-arena-gold/20',
    description: 'Raw aetherical winds warp reality, quickening reflexes and amplifying blows.',
  },
  'Chaotic Winds': {
    icon: Wind,
    colorClass: 'text-primary',
    bgClass: 'bg-primary/10',
    borderClass: 'border-primary/20',
    description: 'Erratic winds buffet the arena, disrupting movement and throwing off attacks.',
  },
  Mirage: {
    icon: Sun,
    colorClass: 'text-arena-gold',
    bgClass: 'bg-arena-gold/10',
    borderClass: 'border-arena-gold/20',
    description: '10% more stamina drain in combat. Illusions penalty initiative.',
  },
  Tornado: {
    icon: Wind,
    colorClass: 'text-arena-blood',
    bgClass: 'bg-arena-blood/10',
    borderClass: 'border-arena-blood/20',
    description: 'Violent swirling winds destroy coordination. 40% more stamina drain.',
  },
  'Meteor Shower': {
    icon: Sparkles,
    colorClass: 'text-arena-gold',
    bgClass: 'bg-arena-gold/10',
    borderClass: 'border-arena-gold/20',
    description: 'Falling stars distract fighters and add chaotic unpredictability.',
  },
  'Solar Flare': {
    icon: Flame,
    colorClass: 'text-destructive',
    bgClass: 'bg-destructive/10',
    borderClass: 'border-destructive/20',
    description: 'A blinding flash bakes the arena. 50% more stamina drain.',
  },
  'Abyssal Gloom': {
    icon: Moon,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    description: 'Impenetrable supernatural darkness swallows the arena.',
  },
  'Cursed Miasma': {
    icon: CloudFog,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    description: 'A vile purple miasma clings to the arena, draining life and hope.',
  },
  Hailstorm: {
    icon: CloudSnow,
    colorClass: 'text-arena-pop',
    bgClass: 'bg-arena-pop/10',
    borderClass: 'border-arena-pop/20',
    description: 'Pummeling hail batters the fighters, hurting momentum and stamina.',
  },
  'Arcane Storm': {
    icon: CloudLightning,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    description: 'Raw magic warps reality, supercharging strikes and reflexes.',
  },
  'Blood Rain': {
    icon: Droplets,
    colorClass: 'text-destructive',
    bgClass: 'bg-destructive/10',
    borderClass: 'border-destructive/20',
    description: 'Red rain slickens the sand. Violence feels inevitable.',
  },
  'Locust Swarm': {
    icon: Factory,
    colorClass: 'text-arena-pop',
    bgClass: 'bg-arena-pop/10',
    borderClass: 'border-arena-pop/20',
    description: 'A blinding swarm descends upon the arena, gnawing at everything.',
  },
  Rainbow: {
    icon: Sparkles,
    colorClass: 'text-arena-gold',
    bgClass: 'bg-arena-gold/10',
    borderClass: 'border-arena-gold/20',
    description: 'A beautiful rainbow spans the sky. Spirits are high.',
  },
  'Ember Rain': {
    icon: Flame,
    colorClass: 'text-arena-blood',
    bgClass: 'bg-arena-blood/10',
    borderClass: 'border-arena-blood/20',
    description: 'Glowing embers rain down from the sky, searing the sand and fighters alike.',
  },
  'Wildfire Smoke': {
    icon: Flame,
    colorClass: 'text-arena-blood',
    bgClass: 'bg-arena-blood/10',
    borderClass: 'border-arena-blood/20',
    description: 'Thick smoke reduces visibility and chokes the lungs.',
  },
  'Gravity Anomaly': {
    icon: Sparkles,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    description: 'The laws of physics break down, making combat wildly unpredictable.',
  },
  'Blood Fog': {
    icon: CloudFog,
    colorClass: 'text-destructive',
    bgClass: 'bg-destructive/10',
    borderClass: 'border-destructive/20',
    description: 'A crimson fog obscures vision and incites a frantic, bloody panic.',
  },
  'Shimmering Heat': {
    icon: Sun,
    colorClass: 'text-arena-blood',
    bgClass: 'bg-arena-blood/10',
    borderClass: 'border-arena-blood/20',
    description: 'A rippling heatwave blurs vision and exhausts fighters.',
  },
  'Crystal Rain': {
    icon: Sparkles,
    colorClass: 'text-primary',
    bgClass: 'bg-primary/10',
    borderClass: 'border-primary/20',
    description: 'Sharp, shimmering crystals fall from the sky. Cuts armor, drains stamina.',
  },
  'Rain of Frogs': {
    icon: CloudRain,
    colorClass: 'text-primary',
    bgClass: 'bg-primary/10',
    borderClass: 'border-primary/20',
    description: 'An absurd rain of frogs causes widespread confusion and slippery footing.',
  },
  'Chaos Storm': {
    icon: Sparkles,
    colorClass: 'text-arena-fame',
    bgClass: 'bg-arena-fame/10',
    borderClass: 'border-arena-fame/20',
    description:
      'A swirling vortex of raw chaos drains stamina and amplifies damage unpredictably.',
  },
  'Whispering Winds': {
    icon: Wind,
    colorClass: 'text-arena-pop',
    bgClass: 'bg-arena-pop/10',
    borderClass: 'border-arena-pop/20',
    description: 'Strange voices carried by the wind heighten paranoia and riposte chances.',
  },
  'Chaos Squall': {
    icon: Sparkles,
    colorClass: 'text-purple-300',
    bgClass: 'bg-purple-300/10',
    borderClass: 'border-purple-300/20',
    description:
      'A chaotic squall of purple energy descends upon the arena, making every shadow twitch.',
  },
};

/**
 *
 */
export function getWeatherConfig(weather: WeatherType | string): WeatherConfig {
  return WEATHER_CONFIG[weather as WeatherType] ?? WEATHER_CONFIG.Clear;
}

export const WEATHER_PENALTIES = {
  RAIN_LUNGE_INITIATIVE: -2,
  DENSE_FOG_RIPOSTE_BONUS: 3,
  DENSE_FOG_LUNGE_BONUS: 2,
  SANDSTORM_AIMED_INITIATIVE: -4,
  BLOOD_MOON_BASHING_DAMAGE: 1.1,
  BLOOD_MOON_SLASHING_DAMAGE: 1.05,
  BLIZZARD_LUNGE_INITIATIVE: -3,
  BLIZZARD_STRIKING_INITIATIVE: -2,
  MANA_SURGE_AIMED_DAMAGE: 1.15,
  RAIN_LUNGE_PENALTY: -0.15,
  DUST_RIPOSTE_PENALTY: -0.1,
  MIST_BASHING_DAMAGE: 0.9,
  GALE_LUNGE_INITIATIVE: -3,
  RAIN_SLASHING_PENALTY: -0.1,
  SANDSTORM_BASHING_BONUS: 0.15,
} as const;
