import { defineConfig } from 'vitest/config';
import path from 'path';
import fs from 'fs';

// Scoped isolation: files that mock modules, stub globals, or need jsdom must
// own their worker — a shared module registry makes vi.mock a no-op once a
// sibling caches the real module, and jsdom/node interleaving breaks RTL
// unmount (measured empirically). Everything else shares workers for speed.
// runnerGroups.json is generated by scripts/test-audit-scan.mjs; drift is
// guarded by testQualityAudit.test.ts.
const runnerGroups = JSON.parse(
  fs.readFileSync(path.resolve(import.meta.dirname, './src/test/_setup/runnerGroups.json'), 'utf-8')
) as { isolated: string[] };
const isolatedGlobs = runnerGroups.isolated.map((f) => '**/' + f.slice('src/test/'.length));

const baseTest = {
  environment: 'node' as const,
  globals: true,
  alias: {
    '@': path.resolve(import.meta.dirname, './src'),
    '#scripts': path.resolve(import.meta.dirname, './scripts'),
  },
  testTimeout: 120000,
  hookTimeout: 10000,
  pool: 'threads' as const,
  dir: './src/test',
};

export default defineConfig({
  plugins: [],
  test: {
    ...baseTest,
    projects: [
      {
        test: {
          name: 'shared',
          // Pure-node files never see a DOM — skip setup.dom.ts entirely.
          setupFiles: ['./src/test/_setup/setup.node.ts'],
          isolate: false,
          include: ['**/*.test.ts', '**/*.test.tsx'],
          exclude: ['node_modules/', '**/e2e/**', '**/*.slow.test.ts', ...isolatedGlobs],
        },
      },
      {
        test: {
          name: 'isolated',
          setupFiles: ['./src/test/_setup/setup.node.ts', './src/test/_setup/setup.dom.ts'],
          isolate: true,
          include: isolatedGlobs,
          exclude: ['node_modules/', '**/e2e/**', '**/*.slow.test.ts'],
        },
      },
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html'],
      exclude: ['node_modules/', 'src/test/', '*.test.ts', '*.test.tsx'],
      // Post-audit baseline (2026-09): 85.3% stmts / 75.2% branches /
      // 79.1% funcs / 86.8% lines. Thresholds sit ~1pt below to allow
      // unrelated drift while still catching real coverage regressions.
      thresholds: {
        statements: 84,
        branches: 74,
        functions: 78,
        lines: 85.5,
      },
    },
  },
});
