import type { TraitDef } from '@/engine/traits';

/** New negative traits — the botch/bad-start pool. Each has a tooltip. */
export const NEW_FLAWS: Record<string, TraitDef> = {
  glass_jaw: {
    id: 'glass_jaw',
    name: 'Glass Jaw',
    description: '−2 parry — a fragile guard that buckles under pressure.',
    effect: { parMod: -2 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  hesitant: {
    id: 'hesitant',
    name: 'Hesitant',
    description: '−1 decisiveness — second-guesses the opening.',
    effect: { decMod: -1 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  short_winded: {
    id: 'short_winded',
    name: 'Short-Winded',
    description: '×1.08 endurance cost — tires quickly.',
    effect: { enduranceMult: 1.08 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  timid: {
    id: 'timid',
    name: 'Timid',
    description: 'Fights cautiously — lower aggression and killing intent.',
    effect: { fightPlanMod: { OE: -3, killDesire: -5 } },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  predictable: {
    id: 'predictable',
    name: 'Predictable',
    description: '−1 riposte — easy to read, slow to counter.',
    effect: { ripMod: -1 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  brittle: {
    id: 'brittle',
    name: 'Brittle',
    description: '−1 defense and tires faster — a body that takes a toll.',
    effect: { defMod: -1, enduranceMult: 1.05 },
    weight: 0.35,
    tier: 'Flaw',
    sign: 'negative',
  },
  wild: {
    id: 'wild',
    name: 'Wild',
    description: '−1 decisiveness — wastes openings on undisciplined swings.',
    effect: { decMod: -1 },
    weight: 0.35,
    tier: 'Flaw',
    sign: 'negative',
  },
  coward: {
    id: 'coward',
    name: 'Coward',
    description: 'Avoids the kill — sharply lower killing intent.',
    effect: { fightPlanMod: { killDesire: -10 } },
    weight: 0.3,
    tier: 'Flaw',
    sign: 'negative',
  },
  clumsy: {
    id: 'clumsy',
    name: 'Clumsy',
    description: '−1 attack — heavy-footed and imprecise.',
    effect: { attMod: -1 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  thin_skinned: {
    id: 'thin_skinned',
    name: 'Thin-Skinned',
    description: '−2 defense when bloodied — falls apart once hurt.',
    effect: { defModLowHp: -2 },
    weight: 0.35,
    tier: 'Flaw',
    sign: 'negative',
  },
};
