export const ARENA_EVENT_CONSTANTS = {
  HAUNTING_WHISPERS_TRIGGER: 18,

  COLLAPSING_PILLAR_TRIGGER: 15,
  CROWD_RIOT_TRIGGER: 15,
  CROWD_RIOT_DAMAGE: 2,
  BLOOD_MOON_LIGHTING_TRIGGER: 1,
  BLOOD_MOON_LIGHTING_DAMAGE: 1.3,
  GEYSER_ERUPTION_TRIGGER: 6,
  SHADOW_TENDRIL_TRIGGER: 20,
  SHADOW_TENDRIL_DRAIN: 5,
  THORN_BARBS_TRIGGER: 10,
  SHIFTING_ROOTS_TRIGGER: 3,
  DEEPENING_MUCK_TRIGGER: 4,
  AQUEDUCT_FLOOD_TRIGGER: 10,
  VOLCANIC_ERUPTION_TRIGGER: 8,
  WHISPERS_OF_MADNESS_TRIGGER: 2,
} as const;
