import type { IRNGService } from '@/engine/core/rng/IRNGService';

const ORIGINS = [
  'Found curled inside a shattered iron bell in the Cathedral of Ash',
  'Raised by graverobbers in the sunken cemetery of Oakhaven',
  'Abandoned in the blood-stained gutters of the Butcher’s Ward',
  'Survived the Winter of Crows by hiding in a hollowed-out tree',
  'Discovered half-drowned in the venomous swamps of the Lower Wastes',
  'Left wrapped in bloodied rags on the steps of the Silent Brothers monastery',
  'Found hiding inside a hollowed-out iron furnace during the Great Purge',
  'Raised in the hidden fighting rings beneath the Crying Slums',
  'Abandoned at the iron grates of the Dross Orphanage during a thunderstorm',
  'Surviving the plague by sleeping among the dead in the open charnel pits',
  'Abandoned at the rusted gates of the Weeping Mother Orphanage',
  'Abandoned in the dripping undercrofts of the Silent Sisters',
  'Raised by debt-collectors in the squalor of the Brass District',
  'Survived the Ashfall by hiding in a forgotten ossuary',
  'Sold to a pit-fighter trainer for a flask of watered wine',
  'Scavenged for broken weapons in the wake of the Iron March',
  'Abandoned at the heavy iron doors of the Weeping Mother Orphanage during a blood moon',
  "Raised in the overcrowded squalor of St. Jude's Home for the Forgotten",
  'Surviving on rats and rain in the crumbling attic of the Sisters of Mercy',
  'Taught to pick pockets and slit purses by the matron of the Cinderhouse Orphanage',
  'Flogged daily at the Blackwood Boys Home until they learned to strike back',
  'Traded to a fighting pit master by the corrupt warden of the Iron Cage Orphanage',
  'Survived the Cinder Plague by hiding in the cathedral catacombs',
  'Raised by feral dogs in the shadow of the Black Iron Foundry',
  'Sold for a handful of copper coins to a traveling beast-tamer',
  'Escaped the fighting pits of the Undercity during a bloody riot',
  'Born in the sunless depths of the Sunken Asylum',
  'Found wandering the ash-choked plains with no memory of their name',
  'Torn from the suffocating grasp of the sunken asylum of Dross',
  'Surviving the Night of Ash by hiding beneath the floorboards of a ruined cathedral',
  'Raised among the stray hounds that roam the forgotten plague wards',
  'Discovered half-starved in the rusted cages of the Black Iron Orphanage',
  'Emerging from the smoke-choked alleys where the unwanted are left to the rats',
  'Found wandering the silent, frozen catacombs below the city',
  'Discovered half-frozen beneath the whispering gargoyles of Blackwood Orphanage',
  'Raised in the sunless undercrofts where the city discards its unwanted',
  'Surviving the Crimson Winter by huddling near the slag heaps of the ironworks',
  'Abandoned at the steps of an asylum during a blood-red eclipse',
  'A product of the soot-stained cloisters, traded for a handful of copper',
  'Raised by silent wardens in the soot-stained cloisters of St. Jude',
  'A forgotten child of the Pyre, left in a burnt-out orphanage cellar',
  'Bred for labor in the iron nurseries of the under-city',
  'Left bound on the steps of the asylum, traded to recruiters for a handful of silver',
  'Found as an infant in the collapsed mines beneath Ironveil',
  'Survived alone in the Ashwood after bandits razed a village',
  'Pulled from the wreckage of a merchant caravan on the Dread Road',
  'A dock rat from the harbor slums of Port Kethara',
  'Discovered wandering the battlefield after the Siege of Thornwall',
  "Born in a debtors' prison, raised by the wardens' charity",
  'The sole survivor of a plague ship that washed ashore near Gulltown',
  'Grew up scrapping for scraps in the fighting pits of Dusthollow',
  'A runaway from a traveling circus, scarred but unbroken',
  'Taken from a slave caravan by arena scouts before reaching market',
  'Left on the steps of the Temple of Iron during a blood moon',
  'Raised feral in the sewers beneath the Colosseum district',
  'Escaped a collapsed quarry at age seven, dragging two others to safety',
  'The child of a disgraced gladiator, born in the shadow of the arena',
  'Found clutching a broken sword in the ruins of Fort Ashenmere',
  'A former temple acolyte who traded prayers for a practice sword',
  'Left at a roadside inn during a summer festival, raised by the kitchen staff',
  'Found in the ruins of a library, clutching a scroll on anatomy',
  'Escaped from a salt mine after a cave-in killed the guards',
  'The child of a fallen knight, found wandering the high mountain passes',
  'A stowaway from the distant Southern Isles, discovered in a spice crate',
  'Born during a solar eclipse, considered an omen of blood and iron',
  'A street urchin who won a bet with an arena recruiter',
  'Found under the floorboards of a tailor shop after a city riot',
  'Raised by a retired trainer in a remote fishing village',
  'Found adrift on a raft in the middle of the Great Sea',
  'Discovered in the heart of a hedge maze, silent and watchful',
  'Sold by starving parents to the Salt Syndicate at age four',
  'Survived the Bone Orchard plague pits by eating the dead',
  'Born in a fighting pit, the afterbirth washed into the sand',
  "Discovered chained in a debtor's basement, fed through a grate",
  'Only survivor of the orphanage fire that claimed thirty souls',
  'Raised by the Silent Sisters in their subterranean hospice',
  "Survived the sinking of the prison hulk 'Black Sepulchre'",
  'Left as an infant in a weapons crate outside the barracks',
  'Discovered huddled inside a hollowed-out beast carcass in the Frostmarches',
  'Pulled from the churning waters of the Weeping Gorge as a toddler',
  'Sold to a gladiator school by scavengers at the tender age of six',
  'Found clinging to the wreckage of a burnt-out monastery',
  'Brought to the city by a nameless mercenary who died the next day',
  'Discovered starving but fiercely guarding a pile of silver coins',
  'Uncovered beneath the foundations of a ruined asylum',
  'Born during the red comet, abandoned to the howling winds',
  'A runaway from the deep mines, eyes unused to the sun',
  'Sole survivor of a cult sacrifice in the forgotten catacombs',
  "Raised in the shadow of the executioner's block",
  'Found wandering the salt flats with no memory of their past',
  'Taken from a raided nomadic tribe in the far deserts',
  'A forgotten child of the Silent Order, marked by their shadow-brands',
  'Surviving the collapse of the Blackwater Sluice through sheer, grim stubbornness',
  'Cast out from the high spires for a crime they refuse to speak of',
  'Found amidst the ash and embers of a burned-out bloodline',
  'A gutter-rat from the stinking alleys of the Lower Wards',
  'Torn from the arms of a condemned heretic at the steps of the Pyre',
  'Raised by scavengers who picked the teeth of the dead in the Bone Wastes',
  'The runt of a fighting pit, fed on raw meat and cruelty',
  "A nameless stowaway discovered half-drowned in a merchant ship's bilge",
  'Left bound and gagged at the crossroads, an offering to dark gods',
  'Raised in the iron-barred nurseries of the Blackwood Workhouse',
  'Survived the cullings at the Bleak House orphanage by hiding in the coal chute',
  'Found abandoned at the gates of the Asylum for the Forgotten',
  'A ward of the state who traded gruel for fistfights in the yard',
  'Escaped the child-labor mills of the Iron Veil district',
  'Raised by the strict matrons of the Sisters of Mercy Orphanage',
  'Sole survivor of a workhouse fire in the lower slums',
  'A former child beggar who learned to bite when corners were tight',
  'Grew up fighting for scraps behind the Grand Colosseum',
  'Left at the steps of the Temple of the Sun, but raised by the shadows',
  "Found shivering in a burnt-out alchemist's lab, clutching a glowing ember",
  'Abandoned to the howling winds of the Jagged Peaks, raised by a solitary hermit',
  'Washed ashore wrapped in the tattered sails of a notorious pirate galley',
  'Discovered sleeping peacefully inside an empty gibbet cage in the lower wards',
  "The final, desperate offering left at the steps of the forgotten Blood God's shrine",
  'Surviving alone on the rat-infested decks of an abandoned plague ship',
  'Found wandering the ash plains, their face stained with soot and silence',
  'Pulled from the churning waters of the Black Sluice by a graverobber',
  'Born in the shadow of the weeping gallows of Highridge',
  'Left in a rusted iron cage outside the Crying Sister Orphanage',
  'Found chewing on leather straps in the ruins of a gladiator pen',
  'Abandoned during the long night of the Ashen Plague',
  'Raised on the brutal scraps of the Iron Pits in the Lower Wards',
  'Discovered half-starved, guarding the corpse of a massive hound',
  'Left shivering in a discarded coal sack near the Silent Keep',
  'Torn from a smuggling ring that traded orphans for obsidian blades',
  'Raised among the nameless urchins who scrub the blood from the colosseum floors',
  'Abandoned at the edge of the Murkwood with only a rusty iron pendant',
  'Discovered hiding in the hollowed chest cavity of a slain wyvern in the Bone Wastes',
  'Tossed into the corpse-carts during the Red Fever, only to crawl back out days later',
  'Raised by the silent, scarred monks of the Obsidian Spire who communicate only in blows',
  'Found gnawing on iron chains in the deepest cells of the Blackwood Asylum',
  'Left bound at the crossroads at midnight to appease the hungry spirits of the wastes',
  'Smuggled out of a besieged city in a barrel of salted meats, emerging hardened and starving',
  'A runaway from the dreaded salt mines, carrying the scars of the whip and a terrifying endurance',
  'Discovered abandoned in a ruined temple, playfully tossing the skulls of long-dead priests',
];

const CHILDHOOD_TRAITS = [
  'would meticulously collect the severed fingers of thieves for good luck',
  'learned to mimic the death rattle of plague victims to scare off bullies',
  'was caught sharpening human bone fragments into makeshift daggers',
  'learned to mask their fear by laughing manically when struck',
  'would systematically break the fingers of thieves who tried to steal their food',
  'perfected the art of striking from the shadows of the orphanage dormitories',
  'would meticulously collect and sharpen shattered glass from the streets',
  'learned to anticipate the exact moment a drunkard would throw a punch',
  'was known for an unnerving, unblinking stare that made older boys back down',
  'would spend nights mapping the patrol routes of the city guard for fun',
  'would collect shattered teeth from the fighting pits as grim trophies',
  'would trace the flight paths of throwing knives with unsettling focus',
  'learned to stitch their own wounds with horsehair and rusty needles',
  'was notorious for hoarding shattered teeth as currency',
  'learned to recognize the smell of poisoned food before taking a bite',
  'would sit motionless for hours watching spiders weave their deadly webs',
  'would systematically dissect caught rodents to understand their anatomy',
  'learned to sleep with a clenched fist and one eye open',
  'was infamous for throwing blinding dust into the eyes of older bullies',
  'would practice parrying strikes with a splintered table leg in the dark',
  'was known for sharpening rusted iron scraps during sermons',
  'learned early that a broken glass bottle commands more respect than tears',
  "would endure the matrons' beatings without making a single sound",
  'would bite the hands of the matrons who tried to wash them',
  'learned to map out exit routes the moment they entered a new room',
  'was caught hoarding rusty nails under the floorboards',
  'was known for stealing bread from the temple kitchen',
  'spent nights watching the stars from the orphanage roof',
  'often got into fights with the older boys and won',
  'preferred the company of stray dogs to other children',
  'secretly practiced with a heavy wooden branch in the woods',
  'would spend hours drawing technical diagrams in the dirt',
  'earned a reputation as a peacemaker among the street urchins',
  'could hold their breath for three minutes in the harbor pits',
  'was obsessed with the stories of the old arena champions',
  'learned to move without making a single sound in the shadows',
  'developed a freakish grip strength from climbing the quarry walls',
  'spent their few coins on medical scrolls instead of food',
  'would sit in silence for hours, observing the birds of prey',
  'was the only one brave enough to explore the haunted ruins',
  'taught themselves to fight by imitating the arena trainees',
  'became a local legend for never backing down from a challenge',
  'would smile while bleeding, as if pain meant nothing',
  'organized the other orphans into a protection racket',
  "could identify every weapon in the trainer's rack by sound alone",
  'kept a tally of scars as if they were coins in a purse',
  'never spoke, but communicated threats with perfect clarity',
  'slept with a rusted dagger beneath a straw pillow every night',
  'showed a terrifyingly high tolerance for pain during beatings',
  'would bite and claw older kids who tried to take their rations',
  'memorized the patrol routes of guards just for the challenge of evading them',
  'never flinched when the master raised a hand',
  'was caught sharpening bone fragments into makeshift shivs',
  'could perfectly mimic the screams of dying men',
  'slept peacefully through the most deafening thunderstorms',
  'was known to stare unblinking at the flickering flames of the hearth',
  'practiced the art of pain by holding hot coals without a sound',
  'would carve intricate tallies of imagined kills into the stone walls',
  'learned the anatomy of survival by dissecting rats in the alleyways',
  'learned to sleep with one eye open after the workhouse riots',
  'would hoard sharp stones and broken glass under their mattress',
  'developed a terrifyingly silent footstep to evade the night watchmen',
  'was known for biting older children who tried to steal their rations',
  "secretly practiced evasion by dodging the matron's cane",
  "learned to read the flow of battle from watching the city watch's street brawls",
  'could accurately predict rain by the throbbing of their many old fractures',
  'spent their days meticulously mapping the blind spots of the local garrison',
  'would purposefully endure beatings to learn how different bones break',
  'developed a terrifying habit of laughing whenever they drew blood',
  'would break their own fingers just to see if they could set them straight',
  "learned to predict a strike by watching the twitch of an opponent's jaw",
  'slept on a bed of river stones to harden their spine',
  'was known for collecting the teeth of feral dogs slain in the alleys',
  'developed a grim fascination with watching executioners hone their axes',
  'learned to fashion razor-sharp shivs from the rusted iron rungs of their crib',
  'developed a terrifyingly serene smile right before physical conflict erupted',
  'was caught repeatedly catching scorpions with their bare hands',
  'would deliberately stand in the freezing rain for hours to test their resolve',
  'learned to perfectly throw jagged rocks with lethal, terrifying accuracy',
];

const DEFINING_MOMENTS = [
  'until they garroted a corrupt slaver with a stolen rosary',
  'realizing that mercy in the fighting pits is merely a slow suicide',
  'waiting for the day they could turn the arena sands into a river of red',
  'until they drowned a corrupt overseer in a vat of boiling lye',
  'realizing that mercy only rewards the weak with an early grave',
  'waiting for the day they could turn the arena sands into a river of red',
  "until they drove a rusted spike through a slaver's boot and walked free",
  'knowing that the roar of the crowd was the only lullaby they ever needed',
  'waiting for the moment the iron portcullis would rise on their destiny',
  'fought off three armed thugs with nothing but a rusted iron spike',
  'stole a discarded combat manual from a dead gladiator and memorized every stance',
  'strangled a corrupt guard with their own rusted chains to escape confinement',
  'won their first real fight by blinding their opponent with a handful of crushed glass',
  'survived a brutal ambush by playing dead among the corpses for three days',
  'stole a broken sword from a fallen gladiator and taught themselves to kill',
  'until the day they dragged their abuser into the light and left them broken',
  'realizing that mercy in the undercity is just an invitation to be killed',
  'waiting for the moment the gates would close and the true test would begin',
  'knowing that the only escape from the gutters was paved in blood',
  'realizing that the only true law of the streets was written in blood',
  'waiting for the moment the arena doors would open and swallow their past',
  "until the day they crushed a street enforcer's windpipe in a brawl over coppers",
  'understanding early that fear is just a weakness waiting to be exploited',
  'until a recruiter saw them handle a practice sword with natural grace',
  'but everything changed when they saved the Headmistress from a fire',
  "growing into a restless youth with a hunger for the arena's glory",
  'waiting for the day they could finally leave the slums behind',
  'now seeking a master who can turn that raw potential into lethality',
  'possessing a gaze that suggests they have seen more than their share of blood',
  'driven by a quiet, burning desire to prove their worth to the world',
  'carrying the weight of their past with a grim, unyielding determination',
  'ready to trade their freedom for the chance to strike back at fate',
  'looking for the one fight that will finally set them free',
  'with a spirit that refuses to be broken by the grinding poverty of the pits',
  'now standing at the threshold of a legacy they are eager to claim',
  'until the day they killed their first man in the pit at age twelve',
  "now seeking the only family that ever mattered—the crowd's roar",
  'carrying the secrets of the dead like armor beneath the skin',
  "driven by a promise made to someone who didn't survive",
  'standing on the threshold where orphan ends and legend begins',
  'finding solace only in the methodical rhythm of violence',
  'realizing that blood spilled in the arena washes away past sins',
  'embracing the fact that survival is only a matter of breaking the other person first',
  'fueled by a hatred of the weakness that once kept them in chains',
  'now hunting the very men who slaughtered their kin',
  'until the arena offered a stage for their beautiful cruelty',
  'carrying a quiet madness that only the sands can soothe',
  'with nothing left to lose and everything to bleed for',
  'ready to carve their name into the annals of history with steel',
  'transforming years of quiet abuse into a singular, razor-sharp focus',
  'understanding that the world only respects the edge of a blade',
  'carrying the cold certainty that everyone bleeds the same color',
  'waiting for the moment the crowd screams a name that was once forbidden',
  'until the day they knocked out the orphanage bully with a single stone',
  'now seeking vengeance on the system that abandoned them',
  'carrying a deep-seated mistrust of authority figures',
  'with a feral hunger that only the arena can satisfy',
  'ready to turn years of neglect into a relentless, driving fury',
  'realizing the only undeniable truth in this world is the edge of a blade',
  'until they watched their only friend die for a handful of copper coins',
  'carrying a burning need to leave a scar upon the world that rejected them',
  'waiting for the moment they can finally look their executioner in the eye',
  'until the day they dragged a dying mentor out of the bloody sands',
  'realizing that a life in the shadows is merely a slow death',
  'now burning with the cold clarity that only comes from true desperation',
  'finding that their truest self is only revealed at the edge of a blade',
  'until they strangled a corrupted guard with the very chains meant to bind them',
  'carrying the heavy burden of a massacre they alone survived in the Lower Wards',
  'now seeking the arena not for glory, but for a public stage to exact a terrible revenge',
  'until they watched the arena gates close behind them, finally feeling safe',
  'carrying the heavy chains of their past not as a burden, but as a weapon',
  'now seeking the silence that only falls over the colosseum after a brutal execution',
  'realizing that pain is simply the currency demanded by the gods of the arena',
];

/**
 * Generate warrior lore by combining a childhood trait and defining moment.
 * @param name - The warrior's name.
 * @param rng - RNG service for random selection.
 * @returns A formatted lore string.
 */
export function generateLore(name: string, rng: IRNGService): string {
  const childhood = rng.pick(CHILDHOOD_TRAITS);
  const defining = rng.pick(DEFINING_MOMENTS);
  return `${name} ${childhood}, ${defining}.`;
}

/**
 * Generate a warrior's origin story.
 * @param rng - RNG service for random selection.
 * @returns An origin string from the ORIGINS pool.
 */
export function generateOrigin(rng: IRNGService): string {
  return rng.pick(ORIGINS);
}
