import { pick } from '@/utils/random';
import type { IRNGService } from '@/engine/core/rng/IRNGService';

const ORIGINS = [
  'Found as an infant in the collapsed mines beneath Ironveil',
  'Survived alone in the Ashwood after bandits razed a village',
  'Pulled from the wreckage of a merchant caravan on the Dread Road',
  'Abandoned at the orphanage gates during the Crimson Winter',
  'A dock rat from the harbor slums of Port Kethara',
  'Discovered wandering the battlefield after the Siege of Thornwall',
  "Born in a debtors' prison, raised by the wardens' charity",
  'The sole survivor of a plague ship that washed ashore near Gulltown',
  'Grew up scrapping for scraps in the fighting pits of Dusthollow',
  'A runaway from a traveling circus, scarred but unbroken',
  'Taken from a slave caravan by arena scouts before reaching market',
  'Left on the steps of the Temple of Iron during a blood moon',
  'Raised feral in the sewers beneath the Colosseum district',
  'Escaped a collapsed quarry at age seven, dragging two others to safety',
  'The child of a disgraced gladiator, born in the shadow of the arena',
  'Found clutching a broken sword in the ruins of Fort Ashenmere',
  'A former temple acolyte who traded prayers for a practice sword',
  'Left at a roadside inn during a summer festival, raised by the kitchen staff',
  'Found in the ruins of a library, clutching a scroll on anatomy',
  'Escaped from a salt mine after a cave-in killed the guards',
  'The child of a fallen knight, found wandering the high mountain passes',
  'A stowaway from the distant Southern Isles, discovered in a spice crate',
  'Born during a solar eclipse, considered an omen of blood and iron',
  'A street urchin who won a bet with an arena recruiter',
  'Found under the floorboards of a tailor shop after a city riot',
  'Raised by a retired trainer in a remote fishing village',
  'Found adrift on a raft in the middle of the Great Sea',
  'Discovered in the heart of a hedge maze, silent and watchful',
  'Whispers of madness from the Asylum for Foundling Wretches',
  'Sold by starving parents to the Salt Syndicate at age four',
  'Survived the Bone Orchard plague pits by eating the dead',
  'Born in a fighting pit, the afterbirth washed into the sand',
  'Discovered chained in a debtor\'s basement, fed through a grate',
  'Only survivor of the orphanage fire that claimed thirty souls',
  'Raised by the Silent Sisters in their subterranean hospice',
  'Survived the sinking of the prison hulk "Black Sepulchre"',
  'Left as an infant in a weapons crate outside the barracks',
  'Discovered huddled inside a hollowed-out beast carcass in the Frostmarches',
  'Pulled from the churning waters of the Weeping Gorge as a toddler',
  'Sold to a gladiator school by scavengers at the tender age of six',
  'Found clinging to the wreckage of a burnt-out monastery',
  'Brought to the city by a nameless mercenary who died the next day',
  'Discovered starving but fiercely guarding a pile of silver coins',
'Uncovered beneath the foundations of a ruined asylum',
  'Born during the red comet, abandoned to the howling winds',
  'A runaway from the deep mines, eyes unused to the sun',
  'Raised in the shadow of the executioner\'s block',
  'Found wandering the salt flats with no memory of their past',
  'Sole survivor of a cult sacrifice in the forgotten catacombs',
  'Taken from a raided nomadic tribe in the far deserts',
'A forgotten child of the Silent Order, marked by their shadow-brands',
  'Surviving the collapse of the Blackwater Sluice through sheer, grim stubbornness',
  'Cast out from the high spires for a crime they refuse to speak of',
  'Found amidst the ash and embers of a burned-out bloodline',
  'A gutter-rat from the stinking alleys of the Lower Wards',
  'Torn from the arms of a condemned heretic at the steps of the Pyre',
  'Raised by scavengers who picked the teeth of the dead in the Bone Wastes',
  'The runt of a fighting pit, fed on raw meat and cruelty',
  'A nameless stowaway discovered half-drowned in a merchant ship\'s bilge',
  'Left bound and gagged at the crossroads, an offering to dark gods',
  'Found shivering in a burnt-out alchemist\'s lab, clutching a glowing ember',
  'Abandoned to the howling winds of the Jagged Peaks, raised by a solitary hermit',
  'Washed ashore wrapped in the tattered sails of a notorious pirate galley',
  'Unearthed alive from a shallow grave behind the old executioner\'s block',
  'Discovered sleeping peacefully inside an empty gibbet cage in the lower wards',
  'The final, desperate offering left at the steps of the forgotten Blood God\'s shrine',
  'Surviving alone on the rat-infested decks of an abandoned plague ship',
  'Found wandering the ash plains, their face stained with soot and silence',
];

const CHILDHOOD_TRAITS = [
  'was known for stealing bread from the temple kitchen',
  'spent nights watching the stars from the orphanage roof',
  'often got into fights with the older boys and won',
  'preferred the company of stray dogs to other children',
  'secretly practiced with a heavy wooden branch in the woods',
  'would spend hours drawing technical diagrams in the dirt',
  'earned a reputation as a peacemaker among the street urchins',
  'could hold their breath for three minutes in the harbor pits',
  'was obsessed with the stories of the old arena champions',
  'learned to move without making a single sound in the shadows',
  'developed a freakish grip strength from climbing the quarry walls',
  'spent their few coins on medical scrolls instead of food',
  'would sit in silence for hours, observing the birds of prey',
  'was the only one brave enough to explore the haunted ruins',
  'taught themselves to fight by imitating the arena trainees',
  'became a local legend for never backing down from a challenge',
  'would smile while bleeding, as if pain meant nothing',
  'organized the other orphans into a protection racket',
  'could identify every weapon in the trainer\'s rack by sound alone',
  'kept a tally of scars as if they were coins in a purse',
  'never spoke, but communicated threats with perfect clarity',
  'slept with a rusted dagger beneath a straw pillow every night',
  'showed a terrifyingly high tolerance for pain during beatings',
  'would bite and claw older kids who tried to take their rations',
  'memorized the patrol routes of guards just for the challenge of evading them',
'would dissect small animals to understand their anatomy',
  'never flinched when the master raised a hand',
  'was caught sharpening bone fragments into makeshift shivs',
  'could perfectly mimic the screams of dying men',
  'slept peacefully through the most deafening thunderstorms',
'was known to stare unblinking at the flickering flames of the hearth',
  'practiced the art of pain by holding hot coals without a sound',
  'would carve intricate tallies of imagined kills into the stone walls',
  'learned the anatomy of survival by dissecting rats in the alleyways',
  'learned to read the flow of battle from watching the city watch\'s street brawls',
  'could accurately predict rain by the throbbing of their many old fractures',
  'spent their days meticulously mapping the blind spots of the local garrison',
  'would purposefully endure beatings to learn how different bones break',
];

const DEFINING_MOMENTS = [
  'until a recruiter saw them handle a practice sword with natural grace',
  'but everything changed when they saved the Headmistress from a fire',
  "growing into a restless youth with a hunger for the arena's glory",
  'waiting for the day they could finally leave the slums behind',
  'now seeking a master who can turn that raw potential into lethality',
  'possessing a gaze that suggests they have seen more than their share of blood',
  'driven by a quiet, burning desire to prove their worth to the world',
  'carrying the weight of their past with a grim, unyielding determination',
  'ready to trade their freedom for the chance to strike back at fate',
  'looking for the one fight that will finally set them free',
  'with a spirit that refuses to be broken by the grinding poverty of the pits',
  'now standing at the threshold of a legacy they are eager to claim',
  'until the day they killed their first man in the pit at age twelve',
  'now seeking the only family that ever mattered—the crowd\'s roar',
  'carrying the secrets of the dead like armor beneath the skin',
  'driven by a promise made to someone who didn\'t survive',
  'standing on the threshold where orphan ends and legend begins',
  'finding solace only in the methodical rhythm of violence',
  'realizing that blood spilled in the arena washes away past sins',
  'embracing the fact that survival is only a matter of breaking the other person first',
  'fueled by a hatred of the weakness that once kept them in chains',
'now hunting the very men who slaughtered their kin',
  'until the arena offered a stage for their beautiful cruelty',
  'carrying a quiet madness that only the sands can soothe',
  'with nothing left to lose and everything to bleed for',
  'ready to carve their name into the annals of history with steel',
'transforming years of quiet abuse into a singular, razor-sharp focus',
  'understanding that the world only respects the edge of a blade',
  'carrying the cold certainty that everyone bleeds the same color',
  'waiting for the moment the crowd screams a name that was once forbidden',
  'realizing the only undeniable truth in this world is the edge of a blade',
  'until they watched their only friend die for a handful of copper coins',
  'carrying a burning need to leave a scar upon the world that rejected them',
  'waiting for the moment they can finally look their executioner in the eye',
];

/**
 * Generate warrior lore by combining a childhood trait and defining moment.
 * @param name - The warrior's name.
 * @param rng - RNG service for random selection.
 * @returns A formatted lore string.
 */
export function generateLore(name: string, rng: IRNGService): string {
  const r = () => rng.next();
  const childhood = pick(CHILDHOOD_TRAITS, r);
  const defining = pick(DEFINING_MOMENTS, r);
  return `${name} ${childhood}, ${defining}.`;
}

/**
 * Generate a warrior's origin story.
 * @param rng - RNG service for random selection.
 * @returns An origin string from the ORIGINS pool.
 */
export function generateOrigin(rng: IRNGService): string {
  return pick(ORIGINS, () => rng.next());
}
