import { FightingStyle } from "@/types/game";

/**
 * Stable Lords — Canonical Narrative Data
 */

export const HIT_LOC_VARIANTS: Record<string, string[]> = {
  "head":      ["HEAD", "JAW", "TEMPLE", "FOREHEAD", "SKULL", "FACE", "THROAT", "NECK", "side of the HEAD", "CHEEK", "BROW", "CHIN", "EAR", "NOSE", "CROWN"],
  "chest":     ["CHEST", "RIBS", "RIGHT RIBCAGE", "LEFT RIBCAGE", "upper BODY", "BREAST", "STERNUM", "COLLARBONE", "SHOULDER BLADE", "UPPER CHEST"],
  "abdomen":   ["STOMACH", "ABDOMEN", "PELVIS", "KIDNEYS", "GROIN", "BELLY", "LOWER BODY", "SOLAR PLEXUS", "MIDSECTION", "SIDE", "FLANK", "GUT"],
  "right arm": ["RIGHT ARM", "RIGHT FOREARM", "RIGHT BICEPS", "RIGHT ELBOW", "RIGHT HAND", "RIGHT WRIST", "RIGHT SHOULDER", "RIGHT KNUCKLES", "RIGHT UPPER ARM"],
  "left arm":  ["LEFT ARM", "LEFT FOREARM", "LEFT BICEPS", "LEFT ELBOW", "LEFT HAND", "LEFT WRIST", "LEFT SHOULDER", "LEFT KNUCKLES", "LEFT UPPER ARM"],
  "right leg": ["RIGHT LEG", "RIGHT THIGH", "RIGHT KNEE", "RIGHT SHIN", "RIGHT BUTTOCKS", "RIGHT HIP", "RIGHT CALF", "RIGHT ANKLE", "RIGHT HAMSTRING"],
  "left leg":  ["LEFT LEG", "LEFT THIGH", "LEFT KNEE", "LEFT SHIN", "LEFT HIP", "LEFT CALF", "LEFT ANKLE", "LEFT HAMSTRING", "LEFT QUADRICEP"],
};

export const STYLE_PBP_DESC: Record<FightingStyle, string> = {
  [FightingStyle.AimedBlow]:      "fights with cold, surgical precision — a devotee of the AIMED BLOW",
  [FightingStyle.BashingAttack]:  "relies on raw crushing power, built for the BASHING ATTACK",
  [FightingStyle.LungingAttack]:  "is an aggressive charger, committed to the LUNGING ATTACK",
  [FightingStyle.ParryLunge]:     "is a patient counter-fighter who favors the PARRY-LUNGE",
  [FightingStyle.ParryRiposte]:   "lives and dies by the blade's edge — a master of PARRY-RIPOSTE",
  [FightingStyle.ParryStrike]:    "uses a disciplined defensive game, striking through openings — PARRY-STRIKE",
  [FightingStyle.SlashingAttack]: "fights in a wide, sweeping style — the fearsome SLASHING ATTACK",
  [FightingStyle.StrikingAttack]: "brings heavy, direct power to bear with the STRIKING ATTACK",
  [FightingStyle.TotalParry]:     "presents an iron fortress of defense, committed to TOTAL PARRY",
  [FightingStyle.WallOfSteel]:    "never stops pressing — the relentless, overwhelming WALL OF STEEL",
};

export const HELM_DESCS: Record<string, string[]> = {
  "leather_cap": ["LEATHER CAP", "battered LEATHER CAP", "worn LEATHER CAP"],
  "steel_cap":   ["STEEL CAP", "etched STEEL CAP", "dented STEEL CAP", "burnished STEEL CAP"],
  "helm":        ["HELM", "spectacular HELM", "visored HELM", "scarred HELM", "battle-worn HELM"],
  "full_helm":   ["FULL HELM", "fearsome FULL HELM", "imposing FULL HELM", "visored FULL HELM"],
};

export type WeaponType = "slash" | "bash" | "thrust" | "fist" | "generic";

export const ATTACK_TEMPLATES: Record<WeaponType, string[]> = {
  slash: [
    "%N unleashes a blinding flurry of cuts with his %W!",
    "%N steps deep inside the guard, whipping his %W in a vicious arc!",
    "%N snaps his wrist, sending the %W blurring towards the neck!",
    "A horrifying display of speed as %N carves a path with his %W!",
    "%N slashes with his %W!",
    "%N slashes an arcing attack with his %W!",
    "%N whips his %W blade back and forth as if to slash his foe to ribbons!",
    "%N makes a slashing attack using his %W!",
    "%N ducks low, his %W slicing suddenly upwards!",
    "%N makes a brilliant twisting slash with his %W!",
    "%N times a cunning attack, %W leaping with deadly force!",
    "%N's %W lunges with awesome cutting power!",
    "%N whirls and strikes backhandedly with his %W!",
    "%N drives his %W in a forward slash!",
    "%N leaps into the air, taking a furious slash with his %W!",
    "%N leaps forward, swinging his %W into a veritable wall of blades!",
    "%N's %W flashes as he takes a sudden vicious slash at his foe!",
    "%N snaps a fast, horizontal cut with his %W!",
    "%N feints, then whips his %W in a vicious diagonal!",
    "%N throws a rising slash with his %W, low to high!",
    "%N pivots on his heel, driving his %W in a tight, brutal backhand!",
    "%N commits to a wide sweeping arc with his %W!",
    "%N steps inside and rips his %W across at close range!",
    "%N drops his shoulder and drives a savage upward cut with his %W!",
    "%N launches a double slash — high then low — with his %W!",
    "%N angles his body and snaps a blindingly fast cut with his %W!",
    "%N rolls his wrist and lets the %W arc in a tight, vicious circle!",
    "%N takes a half-step forward and whips his %W in a flat, brutal cut!",
    "The %W seems to move on its own as %N launches a flowing, multi-arc slash!",
    "%N's whole body uncoils in a spinning slash with his %W!",
    "%N cuts low, then pivots and slashes high — a murderous combination!",
    "%N advances behind a screen of slashes from his %W!",
    "%N snaps a quick forehand cut then immediately follows with a backhand from his %W!",
    "%N lunges forward and rakes his %W in a ripping diagonal!",
    "%N feints low, catching his foe off guard before sweeping his %W high!",
    "%N steps off the centerline, unleashing a horrifying diagonal slash with his %W!",
  ],
  bash: [
    "%N heaves the %W with bone-shattering intent!",
    "%N roars, bringing the %W down like an executioner's maul!",
    "%N steps into the strike, letting the massive weight of the %W do the work!",
    "The arena trembles as %N unleashes a terrifying overhead smash with his %W!",
    "%N bashes with his %W!",
    "%N smashes downward with his %W!",
    "%N takes a swipe with his %W!",
    "%N bats murderously at his foe with his %W!",
    "%N throws his full weight behind his %W in an all-out assault!",
    "%N attacks, whirling the %W with tremendous force!",
    "%N cleverly tries to break his foe's defense with his %W!",
    "%N swings his %W with deadly intent at the target!",
    "%N whips his %W downward in a vicious power smash!",
    "%N steps in and brings his %W crashing down with both hands!",
    "%N winds up and unleashes a thunderous swing with his %W!",
    "%N drives his %W forward in a short, crushing punch!",
    "%N hammers a savage overhand blow with his %W!",
    "%N crashes his %W in from the side, aiming for the ribs!",
    "%N heaves his %W in a wild, momentum-heavy arc!",
    "%N swings his %W in a great looping overhead smash!",
    "%N shuffles forward and drives his %W into a short, brutal uppercut swing!",
    "%N leans into it and unleashes a devastating horizontal sweep with his %W!",
    "%N plants his feet and brings his %W down like a judge's gavel!",
    "%N catches his foe off balance and clubs down with his %W!",
    "%N spins a half-turn and smashes his %W in a backhand arc!",
    "%N feints left and then bombs his %W down from the right!",
    "%N drops his weight low and drives his %W upward in a rising smash!",
    "The sand shakes as %N charges and swings his %W with everything he has!",
    "%N draws his %W back and throws his hips through a thunderous strike!",
    "%N brings his %W around in a terrifying, skull-crushing arc!",
  ],
  thrust: [
    "%N drops his center and drives a blinding lunge with his %W!",
    "%N's %W strikes like a coiled viper!",
    "%N turns his body completely side-on, extending his %W to its absolute limit!",
    "%N lunges wielding an %W!",
    "%N thrusts with his %W!",
    "%N lunges forward with his %W!",
    "%N stabs powerfully upward with his %W!",
    "%N uses his %W to make a deadly jab at his foe!",
    "%N unleashes his %W in a piercingly accurate thrust!",
    "%N strikes forward with his %W, all his weight behind the blow!",
    "%N thrusts his %W forward with an unbelievably deadly force!",
    "%N feints, then springs viciously forward with his %W!",
    "%N catapults forward, %W stabbing cruelly at his foe!",
    "%N leaps into an incredible flesh-splitting lunge with his %W!",
    "%N lunges forward, %W thrusting with incredible speed and accuracy!",
    "%N dives forward, %W stabbing repeatedly with his charge!",
    "%N snaps his arm straight, driving his %W at the gap in his foe's guard!",
    "%N shifts his weight and explodes forward with his %W!",
    "%N launches a controlled, perfectly balanced lunge with his %W!",
    "%N spins his wrist and drives his %W in a twisting thrust!",
    "%N drops into a low crouch and rockets his %W upward!",
    "%N extends fully, every ounce of reach behind his %W!",
    "%N glides forward with footwork as smooth as his thrust, %W aimed true!",
    "%N crosses his feet and lunges — an unorthodox burst of speed with his %W!",
    "%N dips his shoulder and launches a short, vicious punch-thrust with his %W!",
    "The %W snaps forward from %N's hand with the speed of a striking serpent!",
    "%N breaks rhythm and suddenly accelerates, %W driving at the throat!",
    "%N winds his arm back in a slow feint, then fires his %W at lightning speed!",
    "%N advances with a probing jab from his %W — then commits to the real thing!",
    "%N's %W flickers in and out twice before driving home for real!",
    "%N pivots his hips and launches a rising lunge with his %W from a low line!",
    "%N rockets forward, turning his %W into a blurring needle of death!",
  ],
  fist: [
    "%N steps inside the guard and unleashes a horrific combination!",
    "%N grabs his opponent and drives a sickening KNEE into their midsection!",
    "%N PUNCHES from the waist with unbelievable quickness!",
    "%N throws a rock-fisted PUNCH of incredible felling power!",
    "%N hammers down with a ferocious FOREARM smash!",
    "%N focuses all of his power into a devastating KICK!",
    "%N's HANDS flash forward jabbing fiercely at his surprised foe!",
    "%N attacks, FISTS punching with piston-like horse-felling power!",
    "%N throws a piston-like SIDE KICK at his opponent!",
    "%N dives forward, FISTS driving at his opponent with menacing fury!",
    "%N attacks his foe with a pinpoint-accurate ELBOW!",
    "%N snaps a wicked HEADBUTT at his reeling foe!",
    "%N dips and drives a rising UPPERCUT from the floor!",
    "%N spins and delivers a savage HEEL KICK at his opponent!",
    "%N launches a rapid COMBINATION — jab, cross, body shot!",
    "%N feints with his left and detonates a right HOOK at his foe!",
    "%N drops low and fires a brutal BODY SHOT into his opponent's ribs!",
    "%N throws a flying KNEE at his staggered opponent!",
    "%N clinches and slams a short ELBOW into his foe's face!",
    "%N snaps a fast JAB to create distance, then steps in with a hammering CROSS!",
    "%N spins his whole body and releases a devastating SPINNING BACK FIST!",
    "%N stomps forward and drives his KNEE up into his opponent's midsection!",
    "%N opens with a HOOK to the body to drop the guard, then goes upstairs!",
    "%N explodes forward with a wild, crushing OVERHAND right!",
    "%N's FOOT lashes out in a precise front kick to the chest!",
    "%N flurries — both FISTS hammering at his opponent like a storm!",
    "%N closes the distance instantly, detonating a brutal hook!",
  ],
  generic: [
    "%N strikes using his %W!",
    "%N makes an attack with his %W!",
    "%N strikes forward with his %W!",
    "%N lashes out with his %W!",
    "%N presses with his %W!",
    "%N unleashes a fierce strike with his %W!",
    "%N drives an attack home with his %W!",
    "%N throws a dangerous strike with his %W!",
    "%N moves with sudden violence, %W crashing toward his foe!",
    "%N finds an opening and exploits it with his %W!",
  ],
};

// ─── Mastery & Soul-Bond Templates ──────────────────────────────────────────

export const MASTERY_TEMPLATES: Record<string, string[]> = {
  slash: [
    "%N's blade moves with a soul-bonded precision, a perfect arc of steel!",
    "%N guides his edge with unnatural fluidity — the weapon an extension of his own spirit.",
    "A masterful stroke! %N's %W sings through the air in a perfect rhythmic dance.",
    "%N flows into a mastered slash, the steel flickering like a silver flame.",
    "The %W becomes a part of %N — the cut arrives before the thought.",
    "%N's wrist snaps with the effortless authority of ten thousand practice cuts.",
    "The crowd feels it. Something in the quality of that slash — it belongs to a master.",
    "%N reads the entire exchange in an instant and delivers a slash of absolute economy.",
    "The %W is almost lazy in %N's hand — and yet it arrives exactly where it must.",
    "%N's footwork and blade become one flowing motion — a master's cut.",
    "There is no wasted flourish in %N's slash. Only purpose. Only precision.",
    "The steel traces a line so clean and true the crowd doesn't breathe.",
  ],
  bash: [
    "%N delivers a crushing blow with the perfect weight of his mastered %W!",
    "The impact is heavy and true — %N wields his %W with the absolute leverage of a master.",
    "%N's %W descends with the rhythmic thunder of a soul-bound strike!",
    "Force and technique collide as %N hammers home a flawless mastered strike.",
    "No wasted motion — %N's %W finds the mark with horrible mechanical certainty.",
    "%N's entire body becomes a battering ram, the %W merely the point of impact.",
    "The weight behind that strike is inhuman — %N's mastery of the %W is complete.",
    "%N uses gravity, momentum, and years of experience to deliver a perfect blow.",
    "Every muscle fires in sequence as %N brings the %W down with total mastery.",
    "The %W sings a deep, resonant note on impact — %N hit that perfectly.",
    "That was not a swing. That was a lesson in force delivered by a master.",
    "%N's %W lands with an inevitability that only mastery can produce.",
  ],
  thrust: [
    "%N's %W flickers like a serpent's tongue, a mastered thrust of absolute lethality!",
    "With a master's intuition, %N drives the point of his %W through the smallest gap.",
    "%N's steel finds the rhythm of the soul, a piercing strike of lightning speed!",
    "The %W is a needle in %N's hands, guided by a bond beyond simple training.",
    "%N's thrust arrives not where his foe is — but where his foe will be.",
    "A decade of lunges compressed into one instant — %N's %W strikes with terrifying precision.",
    "The crowd catches its breath. That was not a lucky hit. That was mastery.",
    "%N's rear foot pushes, his hips uncoil, his arm extends — a single perfect motion.",
    "The thrust is so clean that the wound is almost an afterthought.",
    "%N's %W finds the gap between heartbeats — pure, mastered timing.",
    "The point of %N's %W follows a line as straight and true as fate itself.",
    "No one in the crowd tracks the %W until it has already arrived.",
  ],
  fist: [
    "%N's hands move in a mastered blur, the rhythm of a true brawler!",
    "A strike of pure intuition! %N's fists find the mark with soul-bound power.",
    "%N's movements are liquid and lethal, his very body a mastered weapon.",
    "The rhythm of the street and the soul — %N's fists are a blur of perfect technique.",
    "%N hits without telegraphing, without hesitation — the strike simply appears.",
    "There is no wasted motion in %N's hands. Each impact is placed with terrible purpose.",
    "The crowd can barely track his hands. %N has crossed into something beyond training.",
    "%N's whole body flows into the strike — hips, shoulder, fist in perfect sequence.",
    "The punch arrives before the crowd can react. That is what mastery looks like.",
    "%N reads his opponent's micro-movement and fires his fist into the exact space it creates.",
    "The sound of the impact is different when %N hits. Heavier. More complete.",
    "%N doesn't swing. He places. The difference is everything.",
  ]
};

export const SUPER_FLASHY_TEMPLATES: string[] = [
  "✨ A DIVINE STRIKE! %N's soul and steel are one — a golden flicker of absolute mastery! ✨",
  "✨ THE HEAVENS WATCH! %N delivers a legendary blow, his %W pulsing with a golden aura! ✨",
  "✨ UNSTOPPABLE! %N's %W finds the soul-rhythm — a strike that will be sung of for ages! ✨",
  "✨ GOLDEN FURY! %N's mastery is absolute, his %W crushing all before it! ✨",
  "✨ PERFECT FORM! The crowd falls silent, awed by the terrifying beauty of %N's technique! ✨",
  "✨ A STRIKE OUT OF LEGEND! %N transcends the merely skilled — this is art! ✨",
  "✨ THE ARENA ERUPTS! %N has delivered a blow that will be spoken of long after this sand is raked! ✨",
  "✨ SUBLIME VIOLENCE! %N's %W moves with a perfection that borders on the divine! ✨",
  "✨ TRANSCENDENCE! In this moment, %N is not a fighter — he is a force! ✨",
  "✨ THE CROWD GASPS! %N transcends mortal limits, %W trailing a golden arc of pure devastation! ✨",
  "✨ A GOD DESCENDS! %N delivers a magnificent, awe-inspiring strike! ✨",
];

export const INI_FEINT_TEMPLATES = [
  "%N feints a high line, drawing his opponent out of position.",
  "%N shows the blade, but it's a clever ruse!",
  "A masterful feint by %N — his opponent bites on the fake!",
  "%N uses a rhythmic twitch to freeze his enemy for a split second.",
  "%N's eyes flick one way, his weapon goes another!",
  "%N shimmers forward then back, forcing an early commitment from his foe.",
  "A false step from %N throws his opponent's timing completely.",
  "%N's hips twist to open the line — his opponent reads it wrong!",
  "%N feints the body, goes high — his foe bought every bit of it.",
  "%N draws back as if to parry, then strikes!",
  "%N's shoulder dips in a convincing fake — his opponent is a step behind.",
  "%N makes a slow, obvious threat — then moves twice as fast as expected!",
  "%N drops his guard just enough to invite a strike, then isn't there.",
  "%N sells the feint with his whole body — his foe commits completely.",
  "%N's footwork creates a false opening — and his opponent takes it!",
  "%N shows a high attack, switches to low at the last instant.",
  "A dummy thrust from %N sets up the real attack perfectly.",
  "%N fakes a retreat then surges forward — his timing is impeccable!",
  "%N's feint draws the parry, and then his real weapon is already moving.",
  "%N bobs once, twice — then strikes on the third beat.",
];

export const EVEN_STATUS = [
  "The warriors appear equal in skill.",
  "The battle is too close to tell.",
  "The warriors appear evenly matched.",
  "There is no decisive victor here yet.",
  "Neither fighter is able to establish a clear advantage.",
  "The sand is stained by both, and neither yields.",
  "The crowd can't call it — the fight hangs perfectly in the balance.",
  "An even exchange — neither warrior gains the upper hand.",
  "Every attack is matched, every blow answered.",
  "The two warriors seem carved from the same hard stone.",
  "The bout could go either way. The crowd senses it.",
  "No quarter given. None taken. The sand says nothing yet.",
  "Both men are bleeding. Neither will admit it matters.",
  "The fighters are locked in step — reading each other, waiting.",
  "The skill gap here is invisible. This one goes to the wire.",
  "Neither warrior can find the edge. The fight grinds on.",
  "A chess match at full speed — neither side gaining ground.",
  "The crowd is exhausted just watching. Neither fighter will break.",
  "Trade for trade. Blow for blow. Nothing separates these two.",
  "Both fighters know the other's game now. Every move is anticipated.",
  "The longer this goes, the more even it looks.",
  "There is no leading combatant. Only two men surviving each other.",
  "The arena falls into a tense hush — this is anyone's fight.",
  "Blood on both faces. Neither man cares.",
];

export const KILL_TEMPLATES = [
  "%A feints low, catching %D off guard before severing their sword-arm at the elbow. The crowd erupts!",
  "A fountain of gore erupts as %A's final strike decapitates %D!",
  "%D looks down at the ruin of their own chest before collapsing dead into the sand. %A is the victor!",
  "The crowd goes wild as %A twists the weapon, ending %D's life in a spray of crimson!",
  "%A shows no mercy, stepping over %D's body to deliver a horrifying, skull-crushing execution!",
  "A final, gurgling breath escapes %D as %A reclaims his weapon from the corpse.",
  "%D falls to their knees, their life spilling onto the sands. %A stands victorious!",
  "The match concludes in horrific fashion as %D is butchered by %A!",
  "With no mercy shown, %A ends %D's misery in a spray of crimson!",
  "The Lords of the Arena nod in approval as %A violently ends the life of %D.",
  "%D is gravely injured!\n%A delivers the killing blow!",
  "%D crumples to the ground, lifeless.\n%A's strike was unerring and final.",
  "%D falls to the arena floor. The wound is mortal.\nSilence grips the crowd.",
  "%D stumbles to the ground!!!\n%D is slain!",
  "%D's armor fails entirely beneath %A's merciless execution!",
  "The arena holds its breath as %A violently ends %D's life in the crimson sand!",
  "%D is severed from the mortal coil by a perfectly placed killing stroke from %A!",
  "%A turns the bout into a slaughter, claiming a gruesome and total victory over %D!",
  "With a terrifying display of lethal force, %A leaves %D lifeless and broken!",
  "%D pitches forward into the sand. He will not rise again.\n%A claims the kill.",
  "A final, dreadful silence falls. %A stands. %D does not.",
  "The crowd goes quiet as %D folds to the earth — the blow was absolute.",
  "%D's struggle ends here. %A delivers a death blow with cold finality.",
  "There is no coming back from that. %A has ended %D.",
  "The arena erupts — %A has killed in spectacular and brutal fashion!",
  "The LORD PROTECTORS turn away. %A has won with terrible completeness.",
  "%D makes one final sound — then nothing. %A has done their worst.",
  "The killing blow lands. The crowd's roar drowns out everything else.",
  "%D's weapon drops first. Then %D follows it into the sand. It is over.",
  "%A steps back. %D does not get up. The bout is finished in blood.",
  "The crimson sand tells the story. %A stands. %D will not.",
  "A killing stroke from %A — clean, final, and without regret.",
  "%D is struck down where he stands. %A claims victory and walks away.",
  "The crowd erupts as %D falls and stays fallen. %A has won by killing blow.",
  "No one in the arena moves for a moment. Then — pandemonium. %A wins!",
  "%A delivers the final strike with awful precision. %D is dead.",
  "The killing blow is decisive, total, and merciless. %A is the victor.",
  "A spray of blood. A body in the sand. %A stands over it all.",
  "%A steps past a fading guard and ends %D's life with a chilling, masterful execution!",
  "%D chokes on a final breath as %A's %W delivers a horrifying, fatal strike!",
  "The arena goes dead silent as %A brutally ends %D in a spectacular spray of crimson!",
];

export const STOPPAGE_TEMPLATES = [
  "%D motions to the LORD PROTECTORS that he cannot continue!\n%A is the victor of the match!",
  "%D is stopped by an outcry from the LORD PROTECTORS!\n%A has won the duel!",
  "%D accepts his loss, jaw clenched to keep from admitting his pain!\n%A is the victor!",
  "%D compliments his victorious foe on a good fight.\n%A has won the duel!",
  "%D surrenders, and offers his hand to his foe.\n%A is the victor of the match!",
  "The ARENAMASTER steps in. %D cannot continue.\n%A is declared the winner!",
  "%D's seconds throw in the cloth. %A takes the bout!",
  "The fight is waved off — %D has taken too much punishment.\n%A wins!",
  "%D raises a trembling hand. The crowd respects the honesty.\n%A wins the bout.",
  "The ARENAMASTER signals the end. %D is done. %A claims the victory.",
  "%D goes to one knee. He cannot answer the count.\n%A wins!",
  "Bleeding badly, %D shakes his head at the corner. %A is declared victor.",
  "The LORD PROTECTORS intervene — %D is in no state to continue.\n%A wins!",
  "%D drops his weapon, signaling an end. %A accepts the surrender.",
  "Enough is enough. The ARENAMASTER stops the contest. %A is victorious!",
  "%D's corner has seen enough — they signal the stoppage.\n%A wins!",
  "The crowd calls for it to be stopped. The ARENAMASTER obliges.\n%A wins!",
  "%D can no longer protect himself. The bout is waved off in favor of %A.",
  "%D collapses and cannot rise. The officials declare %A the winner.",
  "%D gestures to his wound — a clear surrender. %A nods and steps back.",
];

export const EXHAUSTION_TEMPLATES = [
  "%D can no longer keep fighting. Both warriors are spent.\n%A is awarded the bout on points.",
  "Neither warrior can continue! The Arenamaster awards the bout to %A.",
  "Both fighters have given everything. The sand claims them both, but %A had the better of it.",
  "Gasping, arms heavy, %D finally concedes. %A is the winner by exhaustion.",
  "The bout grinds to a halt — neither warrior has anything left. %A edges it on count.",
  "Two empty vessels stand in the sand. The ARENAMASTER points to %A.",
  "Fatigue wins the fight for %A. The bout ends not with a strike, but a surrender to the body.",
  "The crowd is breathless. So are the fighters. %A wins on accumulated punishment.",
  "%D's legs simply stop working. %A, barely upright himself, is called the winner.",
  "It was never going to be pretty. %A just had a little more left than %D.",
  "Both men lean on their weapons, gasping. The ARENAMASTER awards it to %A.",
  "The bout dies quietly from exhaustion. %A edges %D on the count.",
  "The warriors have fought themselves to nothing. %A takes the decision.",
  "%D's body gives out before his will does. %A is named the winner.",
  "The sand remembers them both. The scorers remember %A.",
  "Arms heavy, lungs burning — %D concedes the decision to %A.",
  "Neither man could finish it. The ARENAMASTER gives the nod to %A.",
  "%A and %D have emptied themselves completely. The judges favor %A.",
  "The bout exhausts itself before either fighter can. %A wins by margin.",
  "A slow, brutal grind — and at the end, %A had the edge.",
];

export const POPULARITY_TEMPLATES = {
  great:    "%N's popularity has greatly increased!",
  normal:   "%N's popularity has increased.",
  marginal: "%N's popularity has marginally increased.",
};

export const SKILL_LEARNS = [
  "%N learned an ATTACK skill.",
  "%N learned a PARRY skill.",
  "%N learned a DEFENSIVE action.",
  "%N learned an INITIATIVE routine.",
  "%N learned a RIPOSTE technique.",
  "%N learned a DECISIVENESS concept.",
  "%N picked up a new ATTACK combination.",
  "%N has developed a sharper PARRY instinct.",
  "%N learned to read an opponent's INITIATIVE better.",
  "%N refined a RIPOSTE timing he hadn't noticed before.",
  "%N internalized a new DEFENSIVE footwork pattern.",
  "%N studies how his last ATTACK landed and adjusts.",
  "%N's ATTACK sharpens as he finds the right rhythm.",
  "Something clicks — %N's PARRY mechanics improve mid-fight.",
  "%N recognizes a gap in his DEFENSE and mentally notes it.",
  "A near-miss teaches %N a new INITIATIVE read.",
  "%N adapts his RIPOSTE timing to match his foe's style.",
  "Hard experience teaches %N a new ATTACK angle.",
  "%N's pain is his teacher — he learns a DEFENSIVE adjustment.",
  "Under pressure, %N discovers a new way to use his INITIATIVE.",
];

export const TRADING_BLOWS = [
  "The two warriors fiercely trade attacks and parry.",
  "Both attack, weapons strike and rebound, strike and rebound.",
  "The warriors attack together, almost grappling with each other.",
  "The weapons lock together in a struggle for supremacy.",
  "The weapons lock together in a test of strength.",
  "A ferocious exchange — blow for blow, neither budging.",
  "Steel meets steel in a furious, close-quarters storm!",
  "The crowd is on their feet as the warriors trade punishing blows!",
  "An ugly brawl in the sand — both warriors land, both warriors feel it.",
  "The fighters batter at each other in a grim war of attrition.",
  "No grace here — just two men trying to outlast each other.",
  "The sound of impact after impact fills the arena. Neither man retreats.",
  "They hammer at each other like rivals who have waited years for this.",
  "A savage exchange at close range — both fighters staggered but upright.",
  "A wild flurry — the crowd roars as both men take and give in equal measure!",
  "Neither warrior takes a backward step. The exchange is savage and mutual.",
  "They meet in the center of the sand and PUNISH each other.",
  "Weapons clatter and spark as the two fighters go toe to toe!",
  "A breathtaking exchange — neither man will back down!",
  "The arena holds its breath as both warriors throw everything at each other.",
  "They're both bleeding. They both keep going. The crowd loves it.",
  "A furious, grinding close-quarters battle — neither man gaining the edge.",
  "Three hard blows traded. Three more land. Neither warrior yields an inch.",
  "The sand flies as both fighters commit to a wild, total exchange.",
  "The crowd screams as the warriors crash into each other with full force.",
  "Each hit they land, they absorb one in return. Neither cares.",
  "A grinding exchange — the kind that leaves marks for weeks.",
  "Back and forth, back and forth. The crowd is delirious.",
];

export const STALEMATE_LINES = [
  "The fighters slowly circle each other, looking for a weakness.",
  "The fighters step back from each other for a moment.",
  "The action comes to a halt as the warriors reorient themselves.",
  "The warriors stand quietly and study each other.",
  "A tense pause — both men catching their breath and reading the other.",
  "The crowd murmurs as the fighters circle, neither willing to commit.",
  "A moment of stillness descends on the arena sand.",
  "Both warriors have tested each other. Now they wait.",
  "The fighters feint and probe, neither willing to overcommit.",
  "A long beat of silence before the storm resumes.",
  "Boots scrape sand as both fighters reset their stances.",
  "The arena quiets. Everyone can feel the next exchange coming.",
  "The two fighters circle, taking stock. This is far from over.",
  "A cautious moment — both men have learned respect for the other.",
  "The warriors reset, eyes locked, each waiting for the other to flinch.",
  "Slow footwork as both men look for the gap they haven't found yet.",
  "The crowd is almost as tense as the fighters. No one breathes.",
  "A strange quiet settles — then a boot drags the sand, and it begins again.",
  "Eye contact. Stillness. Then the slow, dangerous circling resumes.",
  "Neither man commits. Neither man retreats. The sand between them grows charged.",
  "The pause stretches. The crowd grows restless. Then — movement.",
  "Two seasoned fighters assessing. The next exchange will matter.",
  "The warriors catch their breath in silence, weapons raised, eyes watchful.",
  "This is the moment before the moment. Both fighters know it.",
];

export const WINNER_TAUNTS = [
  "%N roars, 'Who else wants to die today?!'",
  "%N wipes the blood from their face and sneers, 'Too easy.'",
  "%N points their weapon at the VIP box and bows deeply.",
  "%N kicks the fallen opponent and laughs maniacally.",
  "%N says, 'Another blow and I'll send you to Ahringol!'",
  "%N says, 'And that is how a real warrior fights. Pay attention next time.'",
  "%N says, 'That was a well fought, and honorable fight.'",
  "%N laughs, 'Oh, this is PRICELESS! Did someone actually tell you you could FIGHT?'",
  "%N growls, 'Are you even human?'",
  "%N grates, 'Try that again, dog!'",
  "%N salutes the audience, then offers a hand to his fallen foe.",
  "%N says nothing. He just looks down at his beaten opponent for a long moment.",
  "%N spits sand and raises his weapon to the roaring crowd.",
  "%N wipes blood from his face and says, 'Not bad. Almost.'",
  "%N addresses the crowd directly, arms wide, soaking in their adulation.",
  "%N steps over his defeated foe and walks to the center of the arena.",
  "%N says, 'Next time, bring someone who can actually hurt me.'",
  "%N sheathes his weapon slowly and deliberately, back already turned.",
  "%N calls out to no one in particular, 'Who else wants to try?'",
  "%N breathes hard for a moment, then straightens and smiles.",
  "%N raises a fist to the crowd, blood still on his knuckles.",
  "%N crouches beside his fallen foe and says something only they can hear.",
  "%N strides the length of the arena, weapon aloft, working the crowd.",
  "%N tilts his head back and roars at the sky.",
  "%N takes a knee briefly — not in defeat, but in private acknowledgment.",
  "%N flicks blood from his blade and sheathes it without looking at his foe.",
  "%N grabs his fallen foe's weapon and holds both aloft to the crowd.",
  "%N laughs — a genuine, delighted sound — and bows to all four corners.",
  "%N points to his own stablemaster and nods. A private acknowledgment.",
  "'Your reputation lied,' %N says flatly, stepping over the body.",
  "%N simply walks away. No flourish. The crowd fills the silence.",
  "'Tell your stablemaster to train you better next time,' %N says with a smirk.",
];

export const LOSER_TAUNTS = [
  "%N spits, 'May maggots partake of your corpse as they have with your ancestors!'",
  "%N exclaims, 'Give it up now, wimp, before I rip your face off!'",
  "%N bellows his frustration.",
  "%N mutters a desperate prayer!",
  "%N reels with the fury of combat!",
  "%N howls like a maddened beast!",
  "%N spits blood and refuses to look away.",
  "%N grits his teeth and squares up for another exchange.",
  "%N curses under his breath, circling again.",
  "%N screams in defiance at the crowd.",
  "%N shakes his head and tries to clear the pain from his eyes.",
  "%N roars something wordless at his foe.",
  "%N stumbles but refuses to go down.",
  "%N spits, 'Is that the best you have?'",
  "%N breathes through the pain and raises his weapon again.",
  "%N growls low — a dangerous, cornered sound.",
  "%N's hands shake, but his eyes are steady.",
  "%N wipes blood from his brow and gestures his foe forward.",
  "'Not done yet,' %N rasps, refusing to yield.",
  "%N spits a tooth into the sand and grins.",
  "%N snarls something in a language no one recognizes.",
  "%N's legs nearly buckle — but he steadies himself on pure spite.",
  "%N beats his own chest and lets out a battle cry.",
  "%N points a trembling weapon at his opponent and holds the line.",
];

export const PRESSING_TEMPLATES = [
  "Our brawny gladiator is pressing his foe to the limit!",
  "%N can't believe that this guy has not surrendered!",
  "%N fights with the cunning of desperation!",
  "%N presses the attack relentlessly, giving his foe no room to breathe!",
  "%N smells blood — he presses harder now!",
  "%N has his opponent on the back foot and will not let up!",
  "%N advances, step by relentless step, forcing his foe toward the edge!",
  "%N is relentless — he won't give his opponent a moment to recover!",
  "%N drives his advantage with controlled aggression!",
  "%N has seized the initiative and is not about to let it go!",
  "%N pours it on — his opponent is crumbling under the pressure!",
  "%N is everywhere at once — his foe has nowhere left to go!",
  "There's no breathing room — %N has his opponent penned in!",
  "%N commits fully to the attack, overwhelming his foe!",
  "%N's relentless assault is breaking the other fighter's will!",
  "The crowd feels it — %N has broken through and won't stop!",
];

export const INSIGHT_ST_HINTS = [
  "His parry shatters under your monstrous strength!",
  "Your blade meets staggering resistance — his strength is undeniable.",
  "He carelessly bats away your strike with raw power.",
  "The raw strength in his arms is alarming — your weapon nearly flies free.",
  "He shoves your guard aside like it isn't there. Pure animal strength.",
  "You feel it in your bones — this man is frighteningly powerful.",
  "He catches your strike on his forearm and barely notices.",
  "His grip is iron. You felt that exchange in your whole arm.",
  "He doesn't parry so much as simply stop your weapon with his.",
  "The strength gap is real. He's stronger than he looks.",
  "Your blow lands, but he shrugs it off like rain.",
  "He overwhelms your defense with brute force — technique barely matters to him.",
];

export const INSIGHT_SP_HINTS = [
  "His sluggish movements fail to catch your swift strike.",
  "He moves with blinding speed, leaving you swinging at shadows.",
  "Your reflexes seem barely enough to keep up with his pace.",
  "He's faster than he looks — the strike comes from nowhere.",
  "A flicker of movement — that's all the warning you get.",
  "You can feel his reactions starting to lag. He's slowing down.",
  "His hands are faster than his feet — note that.",
  "You barely track his footwork. He's deceptively quick.",
  "His first step is explosive. Don't give him the first step.",
  "The blow arrives before you expected it. He's faster than you thought.",
  "He's slowing in this heat — press the pace.",
  "His speed is real and dangerous. Respect it.",
];

export const INSIGHT_DF_HINTS = [
  "He clumsily overextends, leaving himself wide open.",
  "His flawless footwork and deft parry leave you bewildered.",
  "His clumsy defense makes him an easy target.",
  "There's a nervousness to his guard — he's not comfortable here.",
  "His defense is a wall of steel. You haven't found the crack yet.",
  "He barely moves to avoid you. His reading of your attacks is unsettling.",
  "That guard has a hole in it — low right. He doesn't protect it.",
  "His parries are getting slower. The defense is eroding.",
  "He reads high attacks brilliantly. Go low.",
  "His footwork is elite. He takes no position twice.",
  "The defense is excellent but reactive — make him guess.",
  "His technique is clean but there's a moment after each parry where he's open.",
];

export const INSIGHT_WL_HINTS = [
  "Despite the punishment, his iron will keeps him standing.",
  "He seems to waver, his resolve breaking under your assault.",
  "There's fear in his eyes now. He knows how this ends.",
  "He is not done. Not yet. That look says everything.",
  "He's bleeding and hurting, but there's something burning in his eyes.",
  "You see the moment he decides — he will not go down without a fight.",
  "He has taken more than most men could and keeps moving forward.",
  "His will is cracking. One more clean exchange should end it.",
  "The pain is visible but he refuses to let it matter.",
  "He is fighting on something beyond endurance now. Respect and beware.",
  "He grits his teeth and squares up again. This one won't quit easily.",
  "There's a wildness in his eyes now — a man with nothing left to lose.",
];
