import type { TraitDef } from '../types';

export const COMMON_TRAITS: Record<string, TraitDef> = {
  iron_stomach: {
    id: 'iron_stomach',
    name: 'Iron Stomach',
    description:
      'Raised on garbage and sour water. Shrugs off stamina loss slightly better than most.',
    effect: { enduranceMult: 0.95 },
    tier: 'Common',
    sign: 'positive',
    weight: 0.8,
  },
  knife_juggler: {
    id: 'knife_juggler',
    name: 'Knife Juggler',
    description: 'Uncanny hand-eye coordination from youth.',
    effect: { attMod: 1 },
    tier: 'Common',
    sign: 'positive',
    weight: 1,
  },
  iron_knuckles: {
    id: 'iron_knuckles',
    name: 'Iron Knuckles',
    description:
      'Calloused fists from countless street brawls. Bonus to unarmed strikes and disarms.',
    effect: { attModEarly: 1, ripMod: 1 },
    tier: 'Common',
    sign: 'positive',
    weight: 0.8,
  },
  adrenaline_surge: {
    id: 'adrenaline_surge',
    name: 'Adrenaline Surge',
    description: '+1 initiative while fresh — their adrenaline spikes right out of the gate.',
    effect: { iniModFresh: 1 },
    weight: 0.8,
    tier: 'Common',
    sign: 'positive',
  },
  quick: {
    id: 'quick',
    name: 'Quick',
    description: '+1 initiative — naturally fast on the draw.',
    effect: { iniMod: 1 },
    weight: 1.0,
    tier: 'Common',
    sign: 'positive',
  },
  bloodthirsty: {
    id: 'bloodthirsty',
    name: 'Bloodthirsty',
    description: '+0.005 to kill window — hungrier for the finish.',
    effect: { killWindowBonus: 0.005 },
    weight: 0.5,
    tier: 'Common',
    sign: 'positive',
  },
  agile: {
    id: 'agile',
    name: 'Agile',
    description: '+1 defense baseline — light on the feet.',
    effect: { defMod: 1 },
    weight: 0.9,
    tier: 'Common',
    sign: 'positive',
  },
  precise: {
    id: 'precise',
    name: 'Precise',
    description: '+1 decisiveness baseline — picks the right opening.',
    effect: { decMod: 1 },
    weight: 0.7,
    tier: 'Common',
    sign: 'positive',
  },
  comboartist: {
    id: 'comboartist',
    name: 'Combo Artist',
    description: '+1 attack when on a hit-streak (≥2 consecutive hits).',
    effect: { attModConsecutiveHits: 1 },
    weight: 0.7,
    tier: 'Common',
    sign: 'positive',
  },
  shadow_step: {
    id: 'shadow_step',
    name: 'Shadow Step',
    description: '+1 defense, −1 damage — favors elusive positioning over heavy strikes.',
    effect: { defMod: 1, dmgBonus: -1 },
    weight: 0.5,
    tier: 'Common',
    sign: 'positive',
  },
};
