import type { TraitDef } from '../types';

export const EXCEPTIONAL_TRAITS: Record<string, TraitDef> = {
  scab_survivor: {
    id: 'scab_survivor',
    name: 'Scab Survivor',
    description: 'Hardened by the slums, giving them an edge when injured.',
    effect: { attModLowHp: 1, defModLowHp: 1 },
    tier: 'Exceptional',
    sign: 'positive',
    weight: 0.4,
  },
  gutters_edge: {
    id: 'gutters_edge',
    name: "Gutter's Edge",
    description:
      'A desperate, wild fighting style born from alleyway brawls. Bonus damage but lowered early defense.',
    effect: { dmgBonus: 1, defModEarly: -1 },
    tier: 'Exceptional',
    sign: 'positive',
    weight: 0.5,
  },
  orphan_vengeance: {
    id: 'orphan_vengeance',
    name: 'Orphan Vengeance',
    description:
      'Driven by a dark past. +2 attack in the late stages and +1% kill window.',
    effect: { attModLate: 2, killWindowBonus: 0.01 },
    tier: 'Exceptional',
    sign: 'positive',
    weight: 0.2,
  },
  orphan_blood: {
    id: 'orphan_blood',
    name: 'Orphan Blood',
    description:
      'Raised in the gutters. Inured to early punishment and fiercely defensive when wounded.',
    effect: { defModEarly: 1, attModLowHp: 1 },
    tier: 'Exceptional',
    sign: 'positive',
    weight: 0.3,
  },
  shadow_walker: {
    id: 'shadow_walker',
    name: 'Shadow Walker',
    description: 'Learned to survive unseen. Swift reflexes and enhanced evasion when fresh.',
    effect: { iniModFresh: 1, decMod: 1 },
    tier: 'Exceptional',
    sign: 'positive',
    weight: 0.2,
  },
  orphan_instinct: {
    id: 'orphan_instinct',
    name: 'Orphan Instinct',
    description:
      '+1 defense in early phase — years of running from danger have sharpened their reflexes.',
    effect: { defModEarly: 1, iniMod: 1 },
    weight: 0.8,
    tier: 'Exceptional',
    sign: 'positive',
  },
  born_in_shadows: {
    id: 'born_in_shadows',
    name: 'Born in Shadows',
    description: '+1 initiative in OPENING phase — used to striking before being seen.',
    effect: { iniModEarly: 1 },
    weight: 0.8,
    tier: 'Exceptional',
    sign: 'positive',
  },
  orphan_shadow: {
    id: 'orphan_shadow',
    name: 'Orphan Shadow',
    description:
      '+1 initiative and +1 decisiveness — forged in the darkest corners of the undercity.',
    effect: { iniMod: 1, decMod: 1 },
    weight: 0.8,
    tier: 'Exceptional',
    sign: 'positive',
  },
  gutter_phantom: {
    id: 'gutter_phantom',
    name: 'Gutter Phantom',
    description: '+1 defense in the early phase and +1 attack when at low HP.',
    effect: { defModEarly: 1, attModLowHp: 1 },
    weight: 0.8,
    tier: 'Exceptional',
    sign: 'positive',
  },
  gutter_born: {
    id: 'gutter_born',
    name: 'Gutter Born',
    description:
      'Forged in the merciless streets. Increased decisiveness and attack in early rounds.',
    effect: { decMod: 1, attModEarly: 1 },
    tier: 'Exceptional',
    sign: 'positive',
    weight: 0.5,
  },
  orphan_fury: {
    id: 'orphan_fury',
    name: 'Orphan Fury',
    description: '+1 attack and +1 initiative when bloodied — fueled by a lifetime of rage.',
    effect: { attModLowHp: 1, iniMod: 1 },
    weight: 0.8,
    tier: 'Exceptional',
    sign: 'positive',
  },
  clutch_survivor: {
    id: 'clutch_survivor',
    name: 'Clutch Survivor',
    description: "+1 attack in LATE phase — they thrive when the crowd thinks it's over.",
    effect: { attModLate: 1 },
    weight: 0.6,
    tier: 'Exceptional',
    sign: 'positive',
  },
  // ── Personality / Combat AI Traits ──
  aggressive: {
    id: 'aggressive',
    name: 'Aggressive',
    description: 'Fights with reckless abandon, favoring strength over defense.',
    effect: { fightPlanMod: { OE: 4, AL: -1, killDesire: 5 }, attrBonus: { ST: 1, WL: 1 } },
    weight: 1.0,
    synergy: ['brutal'],
    antiSynergy: ['tank'],
    tier: 'Exceptional',
    sign: 'positive',
  },
  disciplined_mind: {
    id: 'disciplined_mind',
    name: 'Disciplined',
    description: 'Calm and focused, waiting for the perfect moment to strike.',
    effect: { fightPlanMod: { AL: 3, OE: -1, feintTendency: 5 }, attrBonus: { DF: 1, WL: 1 } },
    weight: 1.0,
    synergy: ['cunning', 'tank'],
    tier: 'Exceptional',
    sign: 'positive',
  },
  cunning: {
    id: 'cunning',
    name: 'Cunning',
    description: 'Favors trickery and misdirection to find the killing blow.',
    effect: {
      fightPlanMod: { feintTendency: 10, AL: 2, killDesire: -2 },
      attrBonus: { SP: 1, DF: 1 },
    },
    weight: 1.0,
    synergy: ['cunning', 'agile'],
    antiSynergy: ['brutal'],
    tier: 'Exceptional',
    sign: 'positive',
  },
  sturdy: {
    id: 'sturdy',
    name: 'Sturdy',
    description: 'An unbreakable wall that outlasts any opponent.',
    effect: { fightPlanMod: { AL: -2, killDesire: -5 }, attrBonus: { CN: 1, SZ: 1 }, defMod: 1 },
    weight: 1.0,
    synergy: ['tank'],
    antiSynergy: ['agile'],
    tier: 'Exceptional',
    sign: 'positive',
  },
  calculated: {
    id: 'calculated',
    name: 'Calculated',
    description: 'Every move is a deliberate setup for a final strike.',
    effect: { fightPlanMod: { feintTendency: 8, AL: 4, OE: -3 }, attrBonus: { SP: 1, DF: 1 } },
    weight: 0.8,
    synergy: ['cunning'],
    antiSynergy: ['brutal'],
    tier: 'Exceptional',
    sign: 'positive',
  },
  resilient: {
    id: 'resilient',
    name: 'Resilient',
    description: 'Absorbs punishment that would fell a lesser warrior.',
    effect: { fightPlanMod: { AL: -2, killDesire: -8 }, attrBonus: { CN: 2 } },
    weight: 0.8,
    synergy: ['tank'],
    antiSynergy: ['agile'],
    tier: 'Exceptional',
    sign: 'positive',
  },
  death_marked: {
    id: 'death_marked',
    name: 'Death-Marked',
    description:
      '+1.2% kill window bonus and +1 decisiveness — an eerie aura that makes their lethal strikes more likely to finish the job.',
    effect: { killWindowBonus: 0.012, decMod: 1, fightPlanMod: { killDesire: 4 } },
    weight: 0.5,
    synergy: ['brutal', 'cunning'],
    antiSynergy: ['tank'],
    tier: 'Exceptional',
    sign: 'positive',
  },
  chaos_touched: {
    id: 'chaos_touched',
    name: 'Chaos Touched',
    description:
      'Touched by strange forces, their strikes grow stronger and wilder as the fight drags on.',
    effect: { dmgBonus: 1, attModLate: 1 },
    weight: 0.1,
    tier: 'Exceptional',
    sign: 'positive',
  },
  gallows_born: {
    id: 'gallows_born',
    name: 'Gallows Born',
    description: '+1% kill window bonus — born under a bad sign, they have an uncanny knack for finding the lethal strike.',
    effect: { killWindowBonus: 0.01, fightPlanMod: { killDesire: 2 } },
    weight: 0.4,
    synergy: ['cunning'],
    tier: 'Exceptional',
    sign: 'positive',
  },
  abyssal_survivor: {
    id: 'abyssal_survivor',
    name: 'Abyssal Survivor',
    description: 'Survived a fall that should have killed them. Fights with desperate ferocity when cornered.',
    effect: { attModLowHp: 2, defModLate: -1 },
    tier: 'Exceptional',
    sign: 'positive',
    weight: 0.3,
  },};
