import type { TraitDef } from '../types';

export const FLAWS_TRAITS: Record<string, TraitDef> = {
  ashen_lung: {
    id: 'ashen_lung',
    name: 'Ashen Lung',
    description: 'Breathed the soot of the forges too long. Prone to coughing fits when exhausted.',
    effect: { enduranceMult: 1.1, attModLate: -1 },
    tier: 'Flaw',
    sign: 'negative',
    weight: 0.4,
  },
  jumpy: {
    id: 'jumpy',
    name: 'Jumpy',
    description: 'Always expects a knife in the back. Better defense and parry, but lower attack.',
    effect: { defMod: 1, parMod: 1, attMod: -1 },
    tier: 'Flaw',
    sign: 'negative',
    weight: 0.7,
  },
  orphan_fragility: {
    id: 'orphan_fragility',
    name: 'Orphan Fragility',
    description: 'Malnourished in youth. Susceptible to early damage.',
    effect: { defModEarly: -1, enduranceMult: 0.9 },
    tier: 'Flaw',
    sign: 'negative',
    weight: 0.1,
  },
  fragile: {
    id: 'fragile',
    name: 'Fragile',
    description: '−2 defense baseline — drops guard easily.',
    effect: { defMod: -2 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  slow: {
    id: 'slow',
    name: 'Slow',
    description: '−1 initiative — late on the draw.',
    effect: { iniMod: -1 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },  // ── New negative traits — the botch/bad-start pool (was traitData/flaws.ts) ──
  glass_jaw: {
    id: 'glass_jaw',
    name: 'Glass Jaw',
    description: '−2 parry — a fragile guard that buckles under pressure.',
    effect: { parMod: -2 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  hesitant: {
    id: 'hesitant',
    name: 'Hesitant',
    description: '−1 decisiveness — second-guesses the opening.',
    effect: { decMod: -1 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  short_winded: {
    id: 'short_winded',
    name: 'Short-Winded',
    description: '×1.08 endurance cost — tires quickly.',
    effect: { enduranceMult: 1.08 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  timid: {
    id: 'timid',
    name: 'Timid',
    description: 'Fights cautiously — lower aggression and killing intent.',
    effect: { fightPlanMod: { OE: -3, killDesire: -5 } },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  predictable: {
    id: 'predictable',
    name: 'Predictable',
    description: '−1 riposte — easy to read, slow to counter.',
    effect: { ripMod: -1 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  brittle: {
    id: 'brittle',
    name: 'Brittle',
    description: '−1 defense and tires faster — a body that takes a toll.',
    effect: { defMod: -1, enduranceMult: 1.05 },
    weight: 0.35,
    tier: 'Flaw',
    sign: 'negative',
  },
  coward: {
    id: 'coward',
    name: 'Coward',
    description: 'Avoids the kill — sharply lower killing intent.',
    effect: { fightPlanMod: { killDesire: -10 } },
    weight: 0.3,
    tier: 'Flaw',
    sign: 'negative',
  },
  clumsy: {
    id: 'clumsy',
    name: 'Clumsy',
    description: '−1 attack — heavy-footed and imprecise.',
    effect: { attMod: -1 },
    weight: 0.4,
    tier: 'Flaw',
    sign: 'negative',
  },
  thin_skinned: {
    id: 'thin_skinned',
    name: 'Thin-Skinned',
    description: '−2 defense when bloodied — falls apart once hurt.',
    effect: { defModLowHp: -2 },
    weight: 0.35,
    tier: 'Flaw',
    sign: 'negative',
  },
};
