import type { TraitDef } from '../types';

export const NOTABLE_TRAITS: Record<string, TraitDef> = {
  // New Narrative Traits
  orphan_street_rat: {
    id: 'orphan_street_rat',
    name: 'Street Rat',
    description: 'Raised in the slums, nimble and hard to hit when desperate.',
    effect: { defModLate: 1, decMod: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.5,
  },
  orphan_pit_fighter: {
    id: 'orphan_pit_fighter',
    name: 'Pit Fighter',
    description: 'Early exposure to brutal fights instills a natural instinct to parry.',
    effect: { parMod: 1, attModEarly: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.5,
  },
  orphan_survivor: {
    id: 'orphan_survivor',
    name: 'Survivor',
    description: 'Surviving a harsh upbringing grants an incredible will to live.',
    effect: { enduranceMult: 0.95, defMod: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.5,
  },
  iron_orphan: {
    id: 'iron_orphan',
    name: 'Iron Orphan',
    description:
      'Forged in the cruelest foundling homes, they fight with a desperate, unyielding survival instinct.',
    effect: { defModLowHp: 1, enduranceMult: 0.95 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.5,
  },
  orphan_resilience: {
    id: 'orphan_resilience',
    name: 'Orphan Resilience',
    description: 'Accustomed to taking a beating and surviving against the odds.',
    effect: { defModLate: 1, enduranceMult: 0.95 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.6,
  },
  hollow_gaze: {
    id: 'hollow_gaze',
    name: 'Hollow Gaze',
    description: 'An unnerving stare that throws opponents off balance when tired.',
    effect: { defModLate: 1, attModLate: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.7,
  },
  gutter_shadow: {
    id: 'gutter_shadow',
    name: 'Gutter Shadow',
    description: 'Accustomed to fighting in cramped, lightless alleys.',
    effect: { attMod: 1, iniMod: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.8,
  },
  // 5 New Personality/Lore Traits

  guttersnipe_cunning: {
    id: 'guttersnipe_cunning',
    name: 'Guttersnipe Cunning',
    description: 'Fights dirty and unpredictable. Harder to pin down in prolonged engagements.',
    effect: { defModLate: 1, iniMod: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.6,
  },
  wild_instinct: {
    id: 'wild_instinct',
    name: 'Wild Instinct',
    description: 'Reacts purely on survival instinct. Fast off the mark, but reckless.',
    effect: { iniMod: 2, parMod: -1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.5,
  },
  shadow_watcher: {
    id: 'shadow_watcher',
    name: 'Shadow Watcher',
    description: 'Always keeps an eye on the unseen. Improved defense early in the fight.',
    effect: { defModEarly: 1, defMod: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 1,
  },
  stone_skin_orphan: {
    id: 'stone_skin_orphan',
    name: 'Stone Skin',
    description: 'Beatings hardened their flesh.',
    effect: { defMod: 0.95 },
    tier: 'Notable',
    sign: 'positive',
    weight: 1,
  },
  starving_dog: {
    id: 'starving_dog',
    name: 'Starving Dog',
    description:
      'Fights like a cornered animal when heavily wounded. Bonus attack when at low health.',
    effect: { attModLowHp: 2, defModLowHp: -1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.6,
  },
  gutter_ghost: {
    id: 'gutter_ghost',
    name: 'Gutter Ghost',
    description: 'Moves unseen in the shadows of the arena. High evasion when healthy.',
    effect: { defMod: 1, parModHighHp: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.6,
  },
  workhouse_resilience: {
    id: 'workhouse_resilience',
    name: 'Workhouse Resilience',
    description: 'Bones hardened by endless grueling labor. Better endurance, defense, and parry.',
    effect: { defMod: 1, parMod: 1, enduranceMult: 0.9 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.6,
  },
  silent_stalker: {
    id: 'silent_stalker',
    name: 'Silent Stalker',
    description: 'Learned to move without a sound in the slums. Increased initiative early.',
    effect: { iniModEarly: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.8,
  },
  feral_endurance: {
    id: 'feral_endurance',
    name: 'Feral Endurance',
    description: 'Used to surviving on nothing but scraps and spite. Reduced endurance drain.',
    effect: { enduranceMult: 0.9 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.8,
  },
  spore_kissed: {
    id: 'spore_kissed',
    name: 'Spore Kissed',
    description: 'Inhaled chaos spores. Improved endurance and decisiveness.',
    effect: { enduranceMult: 0.85, decMod: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.5,
  },
  cornered_rat: {
    id: 'cornered_rat',
    name: 'Cornered Rat',
    description:
      '+1 attack and +1 defense in LATE phase — extremely dangerous when backed into a corner.',
    effect: { attModLate: 1, defModLate: 1 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  asylum_survivor: {
    id: 'asylum_survivor',
    name: 'Asylum Survivor',
    description: '+1 defense and +1 initiative during early phase — hardened by years of survival.',
    effect: { defModEarly: 1, iniMod: 1 },
    weight: 0.8,
    tier: 'Notable',
    sign: 'positive',
  },
  asylum_born: {
    id: 'asylum_born',
    name: 'Asylum Born',
    description: '+1 defense when at low HP — accustomed to surviving desperate situations.',
    effect: { defModLowHp: 1 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  street_rat_cunning: {
    id: 'street_rat_cunning',
    name: 'Street Rat Cunning',
    description:
      '+1 initiative while fresh, +1 decisiveness — always ready to run or strike first.',
    effect: { iniModFresh: 1, decMod: 1 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  street_scrapper: {
    id: 'street_scrapper',
    name: 'Street Scrapper',
    description: '+1 defense in LATE phase — they excel when things get dirty.',
    effect: { defModLate: 1 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  gutter_cunning: {
    id: 'gutter_cunning',
    name: 'Gutter Cunning',
    description: '+1 attack during early phase — strikes fast before the guards arrive.',
    effect: { attModEarly: 1 },
    weight: 0.5,
    tier: 'Notable',
    sign: 'positive',
  },
  gutter_blood: {
    id: 'gutter_blood',
    name: 'Gutter Blood',
    description: '+1 attack against low HP opponents — they can smell the end.',
    effect: { attModLowHp: 1 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  feral_instinct: {
    id: 'feral_instinct',
    name: 'Feral Instinct',
    description:
      '+1 initiative and +1 attack when bloodied (HP < 50%) — reverting to survival instincts learned in the gutters.',
    effect: { iniMod: 1, attModLowHp: 1 },
    weight: 0.8,
    tier: 'Notable',
    sign: 'positive',
  },
  gutter_rat: {
    id: 'gutter_rat',
    name: 'Gutter Rat',
    description:
      '+2 defense in LATE phase — accustomed to outlasting stronger opponents in grueling street fights.',
    effect: { defModLate: 2 },
    weight: 0.8,
    tier: 'Notable',
    sign: 'positive',
  },
  patient: {
    id: 'patient',
    name: 'Patient',
    description: '+2 defense in OPENING phase — sizes up the foe before committing.',
    effect: { defModEarly: 2 },
    weight: 1.0,
    tier: 'Notable',
    sign: 'positive',
  },
  berserker: {
    id: 'berserker',
    name: 'Berserker',
    description: '+2 attack when bloodied (HP < 50%).',
    effect: { attModLowHp: 2 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  stalwart: {
    id: 'stalwart',
    name: 'Stalwart',
    description: '+2 parry while still strong (HP > 75%).',
    effect: { parModHighHp: 2 },
    weight: 0.8,
    tier: 'Notable',
    sign: 'positive',
  },
  heavy_handed: {
    id: 'heavy_handed',
    name: 'Heavy-Handed',
    description: '+1 damage on every successful hit.',
    effect: { dmgBonus: 1 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  disciplined: {
    id: 'disciplined',
    name: 'Disciplined',
    description: '+1 attack in LATE phase — endurance discipline pays off.',
    effect: { attModLate: 1, parMod: 1 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  ironlung: {
    id: 'ironlung',
    name: 'Iron Lung',
    description: '×0.92 endurance cost — efficient breathing.',
    effect: { enduranceMult: 0.92 },
    weight: 0.6,
    tier: 'Notable',
    sign: 'positive',
  },
  iron_grip: {
    id: 'iron_grip',
    name: 'Iron Grip',
    description: '+1 damage, −1 initiative — sacrifices speed for a crushing hold on their weapon.',
    effect: { dmgBonus: 1, iniMod: -1 },
    weight: 0.6,
    tier: 'Notable',
    sign: 'positive',
  },
  cornered_beast: {
    id: 'cornered_beast',
    name: 'Cornered Beast',
    description: '+2 defense when bloodied (HP < 50%) — fights harder when backed into a corner.',
    effect: { defModLowHp: 2 },
    weight: 0.6,
    tier: 'Notable',
    sign: 'positive',
  },
  vengeful: {
    id: 'vengeful',
    name: 'Vengeful',
    description: '+1 damage when bloodied (HP < 50%) — pain only makes them angrier.',
    effect: { attModLowHp: 1, dmgBonus: 1 },
    weight: 0.6,
    tier: 'Notable',
    sign: 'positive',
  },
  stoic: {
    id: 'stoic',
    name: 'Stoic',
    description: '+1 defense in LATE phase — ignores mounting fatigue and pain.',
    effect: { defModLate: 1, parModLate: 1 },
    weight: 0.7,
    tier: 'Notable',
    sign: 'positive',
  },
  // ── New Lore/Personality Traits ──

  // ── New Lore/Personality Traits ──
  silent_one: {
    id: 'silent_one',
    name: 'Silent One',
    description:
      '+1 defense, +1 decisiveness — unnervingly quiet, they waste no breath on roars or taunts.',
    effect: { defMod: 1, decMod: 1, fightPlanMod: { feintTendency: -2 } },
    weight: 0.6,
    synergy: ['cunning'],
    antiSynergy: ['brutal'],
    tier: 'Notable',
    sign: 'positive',
  },
  paranoid: {
    id: 'paranoid',
    name: 'Paranoid',
    description:
      '+2 defense in OPENING phase, but −1 decisiveness overall — constantly expects ambushes.',
    effect: { defModEarly: 2, decMod: -1, fightPlanMod: { AL: -2 } },
    weight: 0.6,
    synergy: ['cunning'],
    tier: 'Notable',
    sign: 'positive',
  },
  cold_eyed: {
    id: 'cold_eyed',
    name: 'Cold-Eyed',
    description:
      '+1 initiative, +1 decisiveness — unnervingly calm, viewing combat purely as geometry and physics.',
    effect: { iniMod: 1, decMod: 1, fightPlanMod: { feintTendency: 4, AL: 2 } },
    weight: 0.6,
    synergy: ['cunning', 'tank'],
    antiSynergy: ['brutal'],
    tier: 'Notable',
    sign: 'positive',
  },
  ashen_lungs: {
    id: 'ashen_lungs',
    name: 'Ashen Lungs',
    description:
      '−10% Endurance, +1 Damage — hacking coughs hide a desperate, brutal strength honed in the soot mines.',
    effect: { enduranceMult: 0.9, dmgBonus: 1 },
    weight: 0.6,
    synergy: ['brutal'],
    tier: 'Notable',
    sign: 'positive',
  },
  alley_stalker: {
    id: 'alley_stalker',
    name: 'Alley Stalker',
    description:
      '+1 Initiative, +0.8% kill window — honed senses from a life of ambushing marks in the shadowed alleys.',
    effect: { iniMod: 1, killWindowBonus: 0.008, fightPlanMod: { AL: 2 } },
    weight: 0.6,
    synergy: ['agile', 'cunning'],
    antiSynergy: ['tank'],
    tier: 'Notable',
    sign: 'positive',
  },
  iron_vein: {
    id: 'iron_vein',
    name: 'Iron Vein',
    description:
      '+1 Defense, +10% Endurance — raised in the deep mines, with bones hardened by labor and scarcity.',
    effect: { defMod: 1, enduranceMult: 0.9, fightPlanMod: { OE: -1 } },
    weight: 0.6,
    synergy: ['tank', 'brutal'],
    antiSynergy: ['agile'],
    tier: 'Notable',
    sign: 'positive',
  },
  gallows_humor: {
    id: 'gallows_humor',
    name: 'Gallows Humor',
    description:
      '+1 Decisiveness, +1 Defense in the LATE phase — laughs in the face of exhaustion and death.',
    effect: { decMod: 1, defModLate: 1 },
    weight: 0.5,
    synergy: ['tank'],
    tier: 'Notable',
    sign: 'positive',
  },
  pit_fighter: {
    id: 'pit_fighter',
    name: 'Pit Fighter',
    description: '+1 damage, +1 defense when bloodied (HP < 50%) — forged in the deepest pits.',
    effect: { dmgBonus: 1, defModLowHp: 1 },
    weight: 0.6,
    synergy: ['brutal'],
    tier: 'Notable',
    sign: 'positive',
  },
  gut_instinct: {
    id: 'gut_instinct',
    name: 'Gut Instinct',
    description: '+1 decisiveness, +1 parry in OPENING phase — preternatural sense for danger.',
    effect: { decMod: 1, parModHighHp: 1, fightPlanMod: { AL: 1 } },
    weight: 0.5,
    tier: 'Notable',
    sign: 'positive',
  },
  orphan_resilience_two: {
    id: 'orphan_resilience_two',
    name: 'Orphan Resilience II',
    description: 'A deeply ingrained instinct to survive when pushed to the absolute edge.',
    effect: { defModLowHp: 2, enduranceMult: 0.9 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.5,
  },
  rust_blooded: {
    id: 'rust_blooded',
    name: 'Rust Blooded',
    description:
      'Accustomed to fighting amidst industrial decay. Immune to minor scrapes and exhaustion.',
    effect: { enduranceMult: 0.9, defMod: 1 },
    tier: 'Notable',
    sign: 'positive',
    weight: 0.6,
  },
};
