/**
 * Removes autogenerated, content-free JSDoc noise from src/**:
 *   1. `@returns The result.` lines
 *   2. `@param <name> - <desc>` lines where <desc> is just the de-camelCased
 *      <name> (junk), e.g. "@param boutId - Bout id." — but NOT real
 *      descriptions like "@param state - The current game state".
 * Any JSDoc block left with no meaningful content is removed entirely.
 *
 * Usage:
 *   bunx tsx scripts/strip-junk-jsdoc.ts --dry   # report only, no writes
 *   bunx tsx scripts/strip-junk-jsdoc.ts         # apply
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

const DRY = process.argv.includes('--dry');
const ROOT = 'src';

function walk(dir: string): string[] {
  const out: string[] = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const s = statSync(p);
    if (s.isDirectory()) out.push(...walk(p));
    else if (/\.tsx?$/.test(p)) out.push(p);
  }
  return out;
}

const alnum = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, '');

/** True if a `@param` line is an autogenerated name-restatement. */
function isJunkParam(line: string): boolean {
  const m = line.match(/^\s*\*\s*@param\s+([A-Za-z0-9_]+)\s*-\s*(.+?)\s*$/);
  if (!m) return false;
  const [, name, desc] = m;
  return alnum(desc) === alnum(name); // desc is just the name spelled out
}

function isJunkReturns(line: string): boolean {
  return /^\s*\*\s*@returns\s+The result\.\s*$/.test(line);
}

let filesChanged = 0;
let linesRemoved = 0;
let blocksRemoved = 0;

for (const file of walk(ROOT)) {
  const src = readFileSync(file, 'utf8');
  const lines = src.split('\n');
  const out: string[] = [];
  let i = 0;
  let changed = false;

  while (i < lines.length) {
    const line = lines[i]!;
    const startsBlock = line.includes('/**');

    if (!startsBlock) {
      out.push(line);
      i++;
      continue;
    }

    // Collect the whole JSDoc block (handles single-line `/** ... */` too).
    const block: string[] = [];
    let j = i;
    while (j < lines.length) {
      block.push(lines[j]!);
      if (lines[j]!.includes('*/')) break;
      j++;
    }

    // Filter junk lines inside the block.
    const kept = block.filter((bl) => {
      if (isJunkReturns(bl)) {
        linesRemoved++;
        changed = true;
        return false;
      }
      if (isJunkParam(bl)) {
        linesRemoved++;
        changed = true;
        return false;
      }
      return true;
    });

    // If nothing meaningful remains, drop the block entirely.
    const meaningful = kept.filter((bl) => {
      const t = bl.replace(/\/\*\*|\*\/|^\s*\*/g, '').trim();
      return t.length > 0;
    });

    if (meaningful.length === 0) {
      blocksRemoved++;
      changed = true;
      // drop block; also drop a single trailing blank line if present
      i = j + 1;
      if (out.length && out[out.length - 1]!.trim() === '') {
        // leave surrounding spacing to prettier
      }
      continue;
    }

    out.push(...kept);
    i = j + 1;
  }

  if (changed) {
    filesChanged++;
    if (!DRY) writeFileSync(file, out.join('\n'));
  }
}

console.log(
  `${DRY ? '[DRY] ' : ''}files changed: ${filesChanged}, junk lines removed: ${linesRemoved}, empty blocks removed: ${blocksRemoved}`
);
