/**
 * Warrior origin stories — data pool for lore generation.
 * Extracted from loreGenerator.ts for SRP separation.
 */

export const CHILDHOOD_TRAITS: string[] = [
  'learned to navigate the city sewers entirely in the pitch black',
  'always kept a sharpened bone hidden in their boot',
  'spoke to the shadows when the orphanage matrons weren\'t looking',
  'developed an iron grip from clinging to the underside of merchant carts',
  'used to meticulously trace the structural flaws in stone walls',
  'slept soundly only when the city',
  'was known for carving the names of their enemies into their own flesh',
  'developed a terrifying habit of laughing whenever they drew blood',
  'would break their own fingers just to see if they could set them straight',
  'slept on a bed of river stones to harden their spine',
  'would steal discarded training weapons from the arena trash heaps',
  'learned to endure the pain of broken bones without making a sound',
  'would silently endure beatings to learn how to absorb blows',
  'learned to craft makeshift shivs from shattered porcelain bowls',
  'was known for biting viciously when cornered by older urchins',
  'would endlessly practice disarming techniques on fellow street urchins',
  'learned to identify weaknesses by observing the limp of aging guards',
  'was known for an unnerving stillness before striking a blow',
  'would hoard rusted nails and sharp stones in their ragged pockets',
  'learned to gauge an opponent',
  'would compulsively trace the veins of slaughtered livestock to learn anatomy',
  'learned to mask their breath entirely when hiding from the night wardens',
  'developed a bone-chilling hum before engaging in street brawls',
  'would gnaw on discarded bones to strengthen their jaw',
  'learned to predict strikes by watching the shadows of passing guards',
  'developed a chillingly blank stare when faced with violence',
  'would compulsively sharpen splinters of bone in the dark',
  'learned to sleep with one eye open after surviving the orphanage riots',
  'was known for an unnerving, silent stare that made the matrons flinch',
  'would sit completely still for hours watching the fighting pit from the rafters',
  'was infamous for never crying out, no matter how severe the punishment',
  'would map out the blind spots of the orphanage guards with obsessive precision',
  'would catch and study the weak points of venomous centipedes',
  'learned to read the mood of the room by the clinking of loose coins',
  'slept clutching a sharpened spoon carved from stolen silver',
  'was famous for slipping out of rusted shackles with dislocated thumbs',
  'would meticulously collect the severed fingers of thieves for good luck',
  'learned to mimic the death rattle of plague victims to scare off bullies',
  'learned to mask their fear by laughing manically when struck',
  'would systematically break the fingers of thieves who tried to steal their food',
  'perfected the art of striking from the shadows of the orphanage dormitories',
  'would meticulously collect and sharpen shattered glass from the streets',
  'learned to anticipate the exact moment a drunkard would throw a punch',
  'was known for an unnerving, unblinking stare that made older boys back down',
  'would spend nights mapping the patrol routes of the city guard for fun',
  'would collect shattered teeth from the fighting pits as grim trophies',
  'would trace the flight paths of throwing knives with unsettling focus',
  'learned to stitch their own wounds with horsehair and rusty needles',
  'was notorious for hoarding shattered teeth as currency',
  'learned to recognize the smell of poisoned food before taking a bite',
  'would sit motionless for hours watching spiders weave their deadly webs',
  'would systematically dissect caught rodents to understand their anatomy',
  'learned to sleep with a clenched fist and one eye open',
  'was infamous for throwing blinding dust into the eyes of older bullies',
  'would practice parrying strikes with a splintered table leg in the dark',
  'was known for sharpening rusted iron scraps during sermons',
  'learned early that a broken glass bottle commands more respect than tears',
  'would endure the matrons',
  'would bite the hands of the matrons who tried to wash them',
  'learned to map out exit routes the moment they entered a new room',
  'was caught hoarding rusty nails under the floorboards',
  'was known for stealing bread from the temple kitchen',
  'spent nights watching the stars from the orphanage roof',
  'often got into fights with the older boys and won',
  'preferred the company of stray dogs to other children',
  'secretly practiced with a heavy wooden branch in the woods',
  'would spend hours drawing technical diagrams in the dirt',
  'earned a reputation as a peacemaker among the street urchins',
  'could hold their breath for three minutes in the harbor pits',
  'was obsessed with the stories of the old arena champions',
  'possessing a disturbing knack for mimicking the dying breaths of pit hounds',
  'showing an unnatural calmness when the orphanage matrons brought out the cane',
  'always caught hoarding sharpened rusted nails beneath their threadbare mattress',
  'whose blank stare terrified even the most hardened street enforcers',
  'learned to move without making a single sound in the shadows',
  'developed a freakish grip strength from climbing the quarry walls',
  'spent their few coins on medical scrolls instead of food',
  'would sit in silence for hours, observing the birds of prey',
  'was the only one brave enough to explore the haunted ruins',
  'taught themselves to fight by imitating the arena trainees',
  'became a local legend for never backing down from a challenge',
  'would smile while bleeding, as if pain meant nothing',
  'organized the other orphans into a protection racket',
  'could identify every weapon in the trainer',
  'kept a tally of scars as if they were coins in a purse',
  'never spoke, but communicated threats with perfect clarity',
  'slept with a rusted dagger beneath a straw pillow every night',
  'showed a terrifyingly high tolerance for pain during beatings',
  'memorized the patrol routes of guards just for the challenge of evading them',
  'never flinched when the master raised a hand',
  'could perfectly mimic the screams of dying men',
  'slept peacefully through the most deafening thunderstorms',
  'was known to stare unblinking at the flickering flames of the hearth',
  'practiced the art of pain by holding hot coals without a sound',
  'would carve intricate tallies of imagined kills into the stone walls',
  'learned the anatomy of survival by dissecting rats in the alleyways',
  'would hoard sharp stones and broken glass under their mattress',
  'developed a terrifyingly silent footstep to evade the night watchmen',
  'was known for biting older children who tried to steal their rations',
  'secretly practiced evasion by dodging the matron',
  'learned to read the flow of battle from watching the city watch',
  'could accurately predict rain by the throbbing of their many old fractures',
  'spent their days meticulously mapping the blind spots of the local garrison',
  'was known for collecting the teeth of feral dogs slain in the alleys',
  'developed a grim fascination with watching executioners hone their axes',
  'learned to fashion razor-sharp shivs from the rusted iron rungs of their crib',
  'was caught repeatedly catching scorpions with their bare hands',
  'would deliberately stand in the freezing rain for hours to test their resolve',
  'learned to perfectly throw jagged rocks with lethal, terrifying accuracy',
  'learned to perfectly mimic the sound of snapping bone',
  'would systematically dismantle discarded clockwork toys',
  'developed a terrifyingly serene smile during the most brutal beatings',
  'developed a terrifyingly serene smile right before physical conflict erupted',
  'would purposefully instigate fights just to study how different people bleed',
  'always watched the shadows instead of the sun',
  'practiced throwing rusted spoons with lethal accuracy',
  'learned to sleep with one eye open and a knife in hand',
  'never cried out when the overseer',
  'learned to sleep with one eye open after the night terrors of the ash-ward',
  'developed an uncanny ability to sense blood before it was spilled',
  'practiced dodging the heavy iron cudgels of the workhouse overseers',
  'memorized the sound of every snapping bone in the fighting pits',
  'learned to predict a strike by watching the shift in a bully’s shoulders',
  'always carried a rusted iron nail hidden under their tongue',
  'slept with their back against the wall and a broken bottle in hand',
  'developed a habit of meticulously counting the breaths of sleeping guards',
  'always won the vicious scrap-fights for table scraps',
  'learned to predict punches by watching the cruel wardens',
  'developed an unnatural pain tolerance from years of lashings',
  'learned to anticipate blows by watching the shadows of the cruel orphanage masters',
  'would instinctively bite anyone who tried to take their meager rations',
  'spent their nights punching the stone walls of their cell until their knuckles calloused',
  'learned to gauge distance by dodging the matron’s iron ruler',
  'memorized the anatomy of beasts while working the charnel pits of the lower wards',
  'developed an unnerving habit of collecting shattered blades from the gutter',
  'learned to move entirely without sound after the great ward riots',
  'survived the bitter winter by huddling next to the crematorium vents',
  'always hid a sharpened stone in their cheek',
  'memorized the patrol routes of the brutal orphanage wardens',
  'developed calluses from punching the stone walls of their cell',
  'learned to sleep with one eye open after the Great Culling',
  'learned to gauge a man’s intent by the dilation of his pupils',
  'developed an eerie stillness to avoid the gaze of the night terrors',
  'memorized the sound of a blade being drawn in the dark',
  'learned to anticipate an ambush by the sudden silence of the alley rats',
  'practiced dodging the heavy iron cudgels of the workhouse overseers in complete darkness',
  'developed an unnatural tolerance for pain by walking barefoot across the slag heaps',
  'always kept a sharpened piece of flint hidden beneath their tongue during sleep',
  'learned to strike first before questions were asked',
  'survived by stealing scraps from the vicious hounds of the Meat Market',
  'developed a keen eye for finding weaknesses in larger foes',
  'flogged daily until they learned how to absorb the pain without flinching',
  'learned to read an opponent by watching the twitch of their jaw',
  'never slept with both eyes fully closed',
  'mastered the art of slipping out of restraints in the dark',
  'developed a haunting stare that made even the guards look away',
  'learned to walk without making a single sound on gravel',
  'would collect the teeth of fallen gladiator beasts as morbid trophies',
  'learned to ignore pain by repeatedly burning their fingers on hot iron',
  'would silently trace the weak points on sleeping guards',
  'developed a chilling, emotionless stare when threatened by older orphans',
  'learned to move entirely without sound after spending weeks hiding from the debt collectors',
  'developed a terrifying pain tolerance from participating in illegal bare-knuckle pit fights as a child',
  "mastered the art of reading micro-expressions from surviving the brutal politics of the beggar king's court",
  'grew unusually strong from hauling bodies out of the plague wards for the morticians',
  'hiding a sharpened spoon in their boots for protection',
  'developed an uncanny tolerance for pain after years of daily beatings',
  'learned to dodge blows by weaving through the crowded, aggressive slums',
  'always observing the subtle twitches and tells of their cruel overseers',
  'learned to dodge before they learned to walk',
  'practiced striking by snapping the necks of giant centipedes in the dark',
  'developed a terrifyingly silent footfall from hiding from debt collectors',
  'developed an uncanny ability to read the twitch of a muscle before a strike',
  'spent their formative years dodging the heavy boots of drunken guards',
  'learned that the only way to stop a beating was to break the hand delivering it',
  'learned to tell the precise weight of an iron cudgel by its whistling sound',
  'developed an unblinking, unsettling stare that unnerved even the cruelest matrons',
  'spent nights quietly scratching structural blueprints of the workhouse into the stone walls',
  'developed a habit of whispering to the blades of their enemies',
  'would purposefully step on broken glass to harden the soles of their feet',
  'was notorious for picking pockets in the middle of a brutal street fight',
  'learned to hold their breath for minutes while hiding in the submerged cisterns',
  'learned to parry blows using shattered chair legs',
  'developed a terrifying stillness before engaging in brawls',
  'would endlessly practice footwork on crumbling parapets',
  'learned to gauge distance by dodging the overseer’s whip',
  'would stare unblinking at the dying embers for hours',
  'learned to read the flow of blood from a fresh wound',
  'collected the rusted iron teeth of the old pit hounds',
  'never made a sound even when walking on broken glass',
];
