/**
 * Warrior origin stories — data pool for lore generation.
 * Extracted from loreGenerator.ts for SRP separation.
 */

export const DEFINING_MOMENTS: string[] = [
  'realizing that mercy in the Undercity was just another word for weakness',
  'until they garroted a corrupt slaver with a stolen rosary',
  'until they drowned a corrupt overseer in a vat of boiling lye',
  'realizing that mercy only rewards the weak with an early grave',
  'until they shattered a merciless overseer',
  'knowing that the roar of the arena is the only justice they will ever see',
  'knowing that only the roar of the colosseum could silence the screams of their past',
  'until they strangled a cruel taskmaster and embraced the arena’s call',
  'until they strangled a cruel matron with a stolen garrote',
  'until they survived the vicious culling of the Warrens',
  'until they turned a rusty nail into a weapon of freedom',
  'realizing that the only family they had was the blade in their hand',
  'until they strangled an abusive warden and stepped into the light',
  'realizing that true power was forged not in gold, but in bone and blood',
  'now seeking to turn the brutality of their past into the roaring adoration of the crowd',
  'waiting to prove that the blood of the slums burns hotter than the gold of kings',
  'until they garroted a cruel overseer and fled into the night',
  'waiting for the moment the iron portcullis of the arena would rise on their true destiny',
  'until they shattered a cruel overseer’s kneecap with a stolen hammer',
  'knowing that blood on the sands washes away the dirt of the slums',
  'until they broke a slaver',
  'waiting to turn the misery of their youth into a spectacle of vengeance',
  'knowing that the arena sands are softer than the stone floors of their youth',
  "until they broke a corrupt warden's jaw with a stolen iron weight",
  'realizing that the only true escape from the slums was paved in shattered bone',
  'until they drowned a slaver in the muddy gutters of the lower wards',
  'knowing that every scar earned in the dark was just practice for the arena',
  'fought off three armed thugs with nothing but a rusted iron spike',
  'stole a discarded combat manual from a dead gladiator and memorized every stance',
  'strangled a corrupt guard with their own rusted chains to escape confinement',
  'won their first real fight by blinding their opponent with a handful of crushed glass',
  'survived a brutal ambush by playing dead among the corpses for three days',
  'stole a broken sword from a fallen gladiator and taught themselves to kill',
  'until the day they dragged their abuser into the light and left them broken',
  'waiting for the moment the gates would close and the true test would begin',
  'realizing that the only true law of the streets was written in blood',
  'waiting for the moment the arena doors would open and swallow their past',
  'until the day they crushed a street enforcer',
  'understanding early that fear is just a weakness waiting to be exploited',
  'until a recruiter saw them handle a practice sword with natural grace',
  'but everything changed when they saved the Headmistress from a fire',
  'growing into a restless youth with a hunger for the arena',
  'waiting for the day they could finally leave the slums behind',
  'now seeking a master who can turn that raw potential into lethality',
  'possessing a gaze that suggests they have seen more than their share of blood',
  'driven by a quiet, burning desire to prove their worth to the world',
  'carrying the weight of their past with a grim, unyielding determination',
  'ready to trade their freedom for the chance to strike back at fate',
  'looking for the one fight that will finally set them free',
  'with a spirit that refuses to be broken by the grinding poverty of the pits',
  'now standing at the threshold of a legacy they are eager to claim',
  'until the day they killed their first man in the pit at age twelve',
  'now seeking the only family that ever mattered—the crowd',
  'carrying the secrets of the dead like armor beneath the skin',
  'driven by a promise made to someone who didn',
  'standing on the threshold where orphan ends and legend begins',
  'finding solace only in the methodical rhythm of violence',
  'realizing that blood spilled in the arena washes away past sins',
  'embracing the fact that survival is only a matter of breaking the other person first',
  'fueled by a hatred of the weakness that once kept them in chains',
  'now hunting the very men who slaughtered their kin',
  'until the arena offered a stage for their beautiful cruelty',
  'carrying a quiet madness that only the sands can soothe',
  'with nothing left to lose and everything to bleed for',
  'ready to carve their name into the annals of history with steel',
  'transforming years of quiet abuse into a singular, razor-sharp focus',
  'understanding that the world only respects the edge of a blade',
  'until the day they knocked out the orphanage bully with a single stone',
  'now seeking vengeance on the system that abandoned them',
  'carrying a deep-seated mistrust of authority figures',
  'with a feral hunger that only the arena can satisfy',
  'ready to turn years of neglect into a relentless, driving fury',
  'realizing the only undeniable truth in this world is the edge of a blade',
  'until they watched their only friend die for a handful of copper coins',
  'carrying a burning need to leave a scar upon the world that rejected them',
  'waiting for the moment they can finally look their executioner in the eye',
  'until the day they dragged a dying mentor out of the bloody sands',
  'realizing that a life in the shadows is merely a slow death',
  'now burning with the cold clarity that only comes from true desperation',
  'finding that their truest self is only revealed at the edge of a blade',
  'until they strangled a corrupted guard with the very chains meant to bind them',
  'carrying the heavy burden of a massacre they alone survived in the Lower Wards',
  'now seeking the arena not for glory, but for a public stage to exact a terrible revenge',
  'until they watched the arena gates close behind them, finally feeling safe',
  'carrying the heavy chains of their past not as a burden, but as a weapon',
  'now seeking the silence that only falls over the colosseum after a brutal execution',
  'realizing that pain is simply the currency demanded by the gods of the arena',
  'until they drove a splintered chair leg through a slaver',
  'realizing that the only true currency in the undercity is pain',
  'waiting for the moment the crowd screams a name they once forgot',
  'carrying the cold certainty that everyone bleeds the same color',
  'waiting for the day they could paint the arena sands with the blood of their oppressors',
  'now driven by a dark vow sworn over the grave of their only friend',
  'until they realized the arena was the only family they needed',
  'waiting for the day they could turn their scars into a spectacle',
  'knowing that the roar of the crowd was the only god left to them',
  'until they drove a shattered bottle into their tormentor',
  'knowing that the roar of the crowd was the only lullaby they ever needed',
  'until they shattered a warden’s jaw with a single, perfectly timed kick',
  'realizing the arena was the only place where their rage was rewarded with silver',
  'until they shattered a slaver',
  'realizing that the only way to escape the slums was over a mountain of broken bodies',
  'until they garroted a brutal taskmaster with their own whip',
  'knowing that the roaring crowd of the arena was the only family they would ever need',
  'until they turned a discarded butcher’s hook into an instrument of vengeance',
  'realizing that the roar of the crowd was simply the sound of survival',
  'knowing that the only way to escape the slums was to build a staircase of bones',
  'discovering that blood on the sands paid better than copper in the mines',
  'strangling a debt collector and realizing their true calling was violence',
  'being thrown into a pit fight to settle a bar tab and surviving against all odds',
  'discovering that the crowd',
  'until they finally realized their lifelong scars were just a map to the arena',
  'realizing that bleeding in the sands paid better than bleeding in the slums',
  'discovering that a rusted spoon could be sharpened into a deadly shiv in the dark',
  'surviving a night in the dog-cages by out-snarling the feral hounds',
  'realizing that mercy in the Undercity was just another word for weakness when their friend was slain',
  'until they broke a taskmaster’s jaw with a stolen cobblestone',
  'realizing that only violence could buy their freedom from the lower wards',
  'when they stood over their first kill and felt nothing but cold relief',
  'until they ambushed a corrupt guard and claimed their first weapon',
  'realizing that the roar of the crowd was the only family they needed',
  'knowing that the arena is the only altar worthy of their sacrifices',
  'until they watched a slaver choke on his own gold',
  'realizing that mercy is a luxury afforded only to the dead',
  'until they dragged a corrupt guard into the shadows and emerged with the keys to their own chains',
  'realizing that the cheers of the arena were the only lullaby they would ever need',
  'knowing that every drop of blood spilled on the sands was a coin paid toward their ultimate freedom',
  'until the day they turned a shattered bone into a makeshift dagger and claimed their first victory',
  'which hardened their resolve to never be helpless again',
  'a trauma that forged an unshakable instinct for survival in the arena',
  'teaching them that the only universal truth is the bite of cold steel',
  'leaving them with a burning desire to prove their worth in blood',
  'until they broke a slaver’s iron collar with a single strike',
  'realizing that fear was a weapon they could wield against the strong',
  'knowing that every drop of blood spilled brings them closer to the throne',
  'until they defended a weaker child by breaking a foreman’s wrist',
  'knowing the only escape from the slums was the blood-soaked sand of the arena',
  'realizing their quick reflexes were meant for killing, not just surviving',
  "until they broke a bully's arm in three places for stealing their crust of bread",
  'realizing that their bloodlust was a talent, not a curse, when the arena recruiters came',
  'knowing that the deafening roar of the bloodsands is the only true applause',
  'until they finally snapped and drove a rusty iron spike through the leg of their abusive taskmaster',
  'realizing that in a city of stone and ash, only the edge of a blade could carve a future',
  'waiting for the day they could wash the stench of the slums off with the blood of champions',
  'knowing that their destiny was to stand over the broken bodies of those who once looked down on them',
  'realizing that the blood on their hands was the only currency that mattered',
  'watching their only friend die, vowing to never be weak again',
  'breaking the nose of the local crime boss in a desperate street brawl',
  'discovering that the roar of the arena crowd could drown out their dark memories',
  'until they strangled an assassin in their sleep to steal their dagger',
  'realizing their only path to glory was paved with the broken bones of their oppressors',
  'knowing that every drop of blood spilled on the sands was a step closer to the throne',
  "until they realized the arena's brutality was just a larger reflection of their childhood",
  'knowing that the iron portcullis of the arena was the only true gate to freedom',
  'understanding that in a world of orphans, only the deadliest are remembered',
  'realizing that the blood-soaked sands offered the only true justice for the forgotten',
  'until they shattered an overseer’s jaw and claimed their first taste of actual power',
  'knowing that their survival depended on weaponizing every ounce of their childhood terror',
  'until they drowned a corrupt warden in the icy waters of the Drowned Bridge',
  'realizing that the only true authority was the sharp edge of a drawn blade',
  'knowing that every scar they gained was simply a map to their eventual revenge',
  'realizing that mercy in the undercity is just an invitation for an early grave',
  'until they strangled a corrupt overseer with their own rusted chains',
  'knowing the shadows hold no fear for those born in them',
  'until they watched their shadow detach and strike first',
  'realizing the only light in the world comes from a sparked blade',
  'waiting for the moment the crowd falls entirely silent in fear',
  'realizing that the blood on their hands was the only currency that mattered',
  'until they strangled a corrupt overseer with their own rusted chains',
  'realizing that mercy in the undercity is just an invitation for an early grave',
  'knowing that the iron portcullis of the arena was the only true gate to freedom',
  'until they shattered an overseer’s jaw and claimed their first taste of actual power',
  ];
