/**
 * Warrior origin stories — data pool for lore generation.
 * Extracted from loreGenerator.ts for SRP separation.
 */

export const ORIGINS: string[] = [
  'Abandoned at the rusted gates of the Blackwood Workhouse',
  'Survived the chilling cullings of the Whispering Vaults',
  'Found swaddled in blood-soaked banners beneath the Weeping Bridge',
  'Abandoned on the jagged rocks beneath the Weeping Gargoyles',
  'Survived the silent culling of the Hollow Hill Orphanage',
  'Sold by desperate parents to the debt-collectors of the Brass Syndicate',
  'Raised amidst the roaring furnaces of the Slag-Pits',
  'Abandoned in the plague-ridden quarantined zone of the Lower Docks',
  'Found wandering aimlessly in the labyrinthine catacombs of the Forgotten Kings',
  'Left on the crumbling steps of the Blackwood Workhouse',
  'Raised in the sunless basements of the Hollow Hill Orphanage',
  'Survived the cruel culling of the Iron Spire Orphanage',
  'Sold by indebted parents to the pit-masters of the Scab District',
  'Abandoned to the feral street-packs of the Whispering Woods',
  'Found shivering beneath the weeping gargoyles of the Ash Quarter',
  'Survived the brutal winters huddled in the exhaust vents of the Grand Forge',
  'Raised as a nameless thrall in the fighting pits of the Undercity',
  'Abandoned beneath the crumbling arches of the Weeping Aqueduct',
  'Found swaddled in blood-stained rags at the gates of the Silent Order',
  'Survived the brutal starvation of the Rat-Catcher Guilds',
  'Sold to the under-barons of the Scab District for a handful of copper',
  'Raised by the feral street-packs of the Warrens',
  'Raised in the haunted dormitories of the Blackbriar Orphanage',
  'Found shivering in the crypts of the Old Abbey',
  'Sold to the fighting pits by the matrons of the Bleak House',
  'Abandoned in the haunted shadows of the Whispering Woods',
  'Raised by the grim grave-keepers of the Obsidian Cemetery',
  'Found clinging to life in the frozen gutters of the North Ward',
  'Survived the terrifying rituals of the Blood Cult of the Undercity',
  'Sold to pit-fighters by indebted parents for a week',
  'Discovered starving in the forgotten cellars of a ruined manor',
  'Raised amidst the chaotic brawls of the Harbor Taverns',
  'Abandoned at the rusted iron gates of the Blackwater Penitentiary',
  'Found shivering in the rusted ruins of the Old Steelworks',
  'Survived by stealing scraps from the vicious hounds of the Meat Market',
  'Born in the sunless cells of the Deep Ward penitentiary',
  'Found clutching a rusted blade in the ruins of the Ashwood Orphanage',
  'Raised by the grim executioners of the High Court',
  'Abandoned in the freezing canals of the Lower Dross',
  'Survived the gruesome cullings of the Black Sun fighting pits',
  'Raised by the soot-stained wardens of the Cinder Keep',
  'Abandoned in the rusted clockwork labyrinth of the Old City',
  'Survived the grueling child-pits of the Salt Wastes',
  'Found shivering among the feral hounds of the Black Market',
  'Raised in the crumbling ruins of the forgotten Bleeding Heart Orphanage',
  'Found abandoned amidst the bone dust of the lower charnel pits',
  'Survived a brutal childhood in the shadow of the executioner',
  'Raised on the violent streets of the Dross Wards by disgraced gladiators',
  'Born in the shadowed cellars of the Blackwood Workhouse',
  'Raised among the soot and cinders of the lower forge district',
  'Left in a rusted iron crib outside the Bloodless Saints Monastery',
  'Found crawling through the charnel heaps of the plague wards',
  'Sold to a fighting pit master for a handful of copper coins and a loaf of bread',
  'Raised by scavengers in the drowned ruins of the Old City',
  'Abandoned near the butcher',
  'Raised in the rat-infested underbelly of the Iron Cages Orphanage',
  'Found shivering beneath the gallows in the central square',
  'Sold to the pit masters by their starving parents for a handful of silver',
  'Raised by feral dogs in the shadow of the colossal colosseum',
  'Survived the grim culling of the Dross Wards by hiding among the dead',
  'Found curled inside a shattered iron bell in the Cathedral of Ash',
  'Raised by graverobbers in the sunken cemetery of Oakhaven',
  'Abandoned in the blood-stained gutters of the Butcher',
  'Survived the Winter of Crows by hiding in a hollowed-out tree',
  'Discovered half-drowned in the venomous swamps of the Lower Wastes',
  'Left wrapped in bloodied rags on the steps of the Silent Brothers monastery',
  'Found hiding inside a hollowed-out iron furnace during the Great Purge',
  'Raised in the hidden fighting rings beneath the Crying Slums',
  'Abandoned at the iron grates of the Dross Orphanage during a thunderstorm',
  'Surviving the plague by sleeping among the dead in the open charnel pits',
  'Abandoned at the rusted gates of the Weeping Mother Orphanage',
  'Abandoned in the dripping undercrofts of the Silent Sisters',
  'Raised by debt-collectors in the squalor of the Brass District',
  'Survived the Ashfall by hiding in a forgotten ossuary',
  'Sold to a pit-fighter trainer for a flask of watered wine',
  'Scavenged for broken weapons in the wake of the Iron March',
  'Abandoned at the heavy iron doors of the Weeping Mother Orphanage during a blood moon',
  'Raised in the overcrowded squalor of St. Jude',
  'Surviving on rats and rain in the crumbling attic of the Sisters of Mercy',
  'Taught to pick pockets and slit purses by the matron of the Cinderhouse Orphanage',
  'Flogged daily at the Blackwood Boys Home until they learned to strike back',
  'Traded to a fighting pit master by the corrupt warden of the Iron Cage Orphanage',
  'Survived the Cinder Plague by hiding in the cathedral catacombs',
  'Sold for a handful of copper coins to a traveling beast-tamer',
  'Escaped the fighting pits of the Undercity during a bloody riot',
  'Born in the sunless depths of the Sunken Asylum',
  'Found wandering the ash-choked plains with no memory of their name',
  'Torn from the suffocating grasp of the sunken asylum of Dross',
  'Surviving the Night of Ash by hiding beneath the floorboards of a ruined cathedral',
  'Raised among the stray hounds that roam the forgotten plague wards',
  'Discovered half-starved in the rusted cages of the Black Iron Orphanage',
  'Emerging from the smoke-choked alleys where the unwanted are left to the rats',
  'Found wandering the silent, frozen catacombs below the city',
  'Discovered half-frozen beneath the whispering gargoyles of Blackwood Orphanage',
  'Raised in the sunless undercrofts where the city discards its unwanted',
  'Surviving the Crimson Winter by huddling near the slag heaps of the ironworks',
  'Abandoned at the steps of an asylum during a blood-red eclipse',
  'A product of the soot-stained cloisters, traded for a handful of copper',
  'Raised by silent wardens in the soot-stained cloisters of St. Jude',
  'A forgotten child of the Pyre, left in a burnt-out orphanage cellar',
  'Bred for labor in the iron nurseries of the under-city',
  'Left bound on the steps of the asylum, traded to recruiters for a handful of silver',
  'Found as an infant in the collapsed mines beneath Ironveil',
  'Survived alone in the Ashwood after bandits razed a village',
  'Pulled from the wreckage of a merchant caravan on the Dread Road',
  'A dock rat from the harbor slums of Port Kethara',
  'Discovered wandering the battlefield after the Siege of Thornwall',
  'Born in a debtors',
  'charity',
  'The sole survivor of a plague ship that washed ashore near Gulltown',
  'Grew up scrapping for scraps in the fighting pits of Dusthollow',
  'A runaway from a traveling circus, scarred but unbroken',
  'Taken from a slave caravan by arena scouts before reaching market',
  'Left on the steps of the Temple of Iron during a blood moon',
  'Raised feral in the sewers beneath the Colosseum district',
  'Escaped a collapsed quarry at age seven, dragging two others to safety',
  'The child of a disgraced gladiator, born in the shadow of the arena',
  'Found clutching a broken sword in the ruins of Fort Ashenmere',
  'A former temple acolyte who traded prayers for a practice sword',
  'Left at a roadside inn during a summer festival, raised by the kitchen staff',
  'Found in the ruins of a library, clutching a scroll on anatomy',
  'Escaped from a salt mine after a cave-in killed the guards',
  'The child of a fallen knight, found wandering the high mountain passes',
  'A stowaway from the distant Southern Isles, discovered in a spice crate',
  'Born during a solar eclipse, considered an omen of blood and iron',
  'A street urchin who won a bet with an arena recruiter',
  'Found under the floorboards of a tailor shop after a city riot',
  'Raised by a retired trainer in a remote fishing village',
  'Found adrift on a raft in the middle of the Great Sea',
  'Discovered in the heart of a hedge maze, silent and watchful',
  'Sold by starving parents to the Salt Syndicate at age four',
  'Survived the Bone Orchard plague pits by eating the dead',
  'Born in a fighting pit, the afterbirth washed into the sand',
  'Discovered chained in a debtor',
  'Only survivor of the orphanage fire that claimed thirty souls',
  'Raised by the Silent Sisters in their subterranean hospice',
  'Survived the sinking of the prison hulk',
  'Left as an infant in a weapons crate outside the barracks',
  'Discovered huddled inside a hollowed-out beast carcass in the Frostmarches',
  'Pulled from the churning waters of the Weeping Gorge as a toddler',
  'Sold to a gladiator school by scavengers at the tender age of six',
  'Found clinging to the wreckage of a burnt-out monastery',
  'Brought to the city by a nameless mercenary who died the next day',
  'Discovered starving but fiercely guarding a pile of silver coins',
  'Uncovered beneath the foundations of a ruined asylum',
  'Born during the red comet, abandoned to the howling winds',
  'A runaway from the deep mines, eyes unused to the sun',
  'Sole survivor of a cult sacrifice in the forgotten catacombs',
  'Raised in the shadow of the executioner',
  'Taken from a raided nomadic tribe in the far deserts',
  'A forgotten child of the Silent Order, marked by their shadow-brands',
  'Surviving the collapse of the Blackwater Sluice through sheer, grim stubbornness',
  'Cast out from the high spires for a crime they refuse to speak of',
  'Found amidst the ash and embers of a burned-out bloodline',
  'A gutter-rat from the stinking alleys of the Lower Wards',
  'Torn from the arms of a condemned heretic at the steps of the Pyre',
  'Raised by scavengers who picked the teeth of the dead in the Bone Wastes',
  'The runt of a fighting pit, fed on raw meat and cruelty',
  'A nameless stowaway discovered half-drowned in a merchant ship',
  'Left bound and gagged at the crossroads, an offering to dark gods',
  'Raised in the iron-barred nurseries of the Blackwood Workhouse',
  'Survived the cullings at the Bleak House orphanage by hiding in the coal chute',
  'Found abandoned at the gates of the Asylum for the Forgotten',
  'A ward of the state who traded gruel for fistfights in the yard',
  'Escaped the child-labor mills of the Iron Veil district',
  'Raised by the strict matrons of the Sisters of Mercy Orphanage',
  'Sole survivor of a workhouse fire in the lower slums',
  'A former child beggar who learned to bite when corners were tight',
  'Grew up fighting for scraps behind the Grand Colosseum',
  'Left at the steps of the Temple of the Sun, but raised by the shadows',
  'Found shivering in a burnt-out alchemist',
  'Abandoned to the howling winds of the Jagged Peaks, raised by a solitary hermit',
  'Washed ashore wrapped in the tattered sails of a notorious pirate galley',
  'Discovered sleeping peacefully inside an empty gibbet cage in the lower wards',
  'The final, desperate offering left at the steps of the forgotten Blood God',
  'Surviving alone on the rat-infested decks of an abandoned plague ship',
  'Found wandering the ash plains, their face stained with soot and silence',
  'Pulled from the churning waters of the Black Sluice by a graverobber',
  'Born in the shadow of the weeping gallows of Highridge',
  'Left in a rusted iron cage outside the Crying Sister Orphanage',
  'Found chewing on leather straps in the ruins of a gladiator pen',
  'Abandoned during the long night of the Ashen Plague',
  'Raised on the brutal scraps of the Iron Pits in the Lower Wards',
  'Discovered half-starved, guarding the corpse of a massive hound',
  'Left shivering in a discarded coal sack near the Silent Keep',
  'Torn from a smuggling ring that traded orphans for obsidian blades',
  'Raised among the nameless urchins who scrub the blood from the colosseum floors',
  'Abandoned at the edge of the Murkwood with only a rusty iron pendant',
  'Discovered hiding in the hollowed chest cavity of a slain wyvern in the Bone Wastes',
  'Tossed into the corpse-carts during the Red Fever, only to crawl back out days later',
  'Raised by the silent, scarred monks of the Obsidian Spire who communicate only in blows',
  'Found gnawing on iron chains in the deepest cells of the Blackwood Asylum',
  'Left bound at the crossroads at midnight to appease the hungry spirits of the wastes',
  'Smuggled out of a besieged city in a barrel of salted meats, emerging hardened and starving',
  'A runaway from the dreaded salt mines, carrying the scars of the whip and a terrifying endurance',
  'Discovered abandoned in a ruined temple, playfully tossing the skulls of long-dead priests',
  'Raised in the sunless depths of the Weeping Undercroft',
  'Abandoned near the slag heaps of the Black Iron Foundry',
  'Found half-starved clutching a rusted nail in the Cinder Wards',
  'Survived the Long Winter by hiding among the forgotten dead',
  'Sold to the fighting pits to settle a drunkard',
  'Abandoned at the iron grates of the Silent Brothers',
  'Raised in the lightless cellars of the Blackwood Orphanage',
  'Abandoned outside the fighting pits wrapped in a bloodied tunic',
  'Survived the great fire of the Lower Wards by hiding in a cistern',
  'Found wandering the ash-choked streets of the Foundry District',
  'Raised by the grim overseers of the Iron Chain workhouse',
  'Born in the ash-choked slums of the Lower Wards, raised on moldy bread and broken promises',
  'Abandoned at the steps of the Silent Sisters, learning early that tears earn only beatings',
  'Survived the Black Fever that wiped out their entire block, leaving them alone in a house of corpses',
  'Raised in the fighting pits beneath the butcher',
  'Cast out by a fallen noble house, forced to scavenge among the very peasants they once ruled',
  'Abandoned at the rusted gates of the Silent Order of St. Jude',
  'Raised by feral hounds in the ruins of the Old Cathedral of the Weeping Mother',
  'Survived the silent culling of the Hollow Hill Orphanage during the long winter',
  'Found swaddled in blood-stained rags in the catacombs beneath the Dross Wards',
  'Raised in the lightless cellars of the Harrow-Home for Wayward Foundlings',
  'Sold to the under-barons of the Scab District for a handful of copper by desperate parents',
  'Abandoned in the soot-stained nursery of the Ashen Ward Workhouse',
  'Survived the brutal starvation of the Rat-Catcher Guilds in the Undercity',
  'Raised in the echoing halls of the Sunken Orphanage of Dross',
  'Abandoned on the rusted steps of the Weeping Maiden Asylum',
  'Survived the cruel lotteries of the Ironwood Foundling Home',
  'Found swaddled in soot in the boiler rooms of the Blackwood Workhouse',
  'Raised by the scarred matrons of the Bleeding Heart Orphanage',
  'Sold to the fighting pits by the debt-ridden wardens of the Hollow Hill Orphanage',
  'Born in the flooded sublevels of the Crying Sisters Orphanage',
  'Abandoned at the iron gates of the Blackwood Asylum during a blood moon',
  'Found swaddled in a tattered slaver’s cloak in the Gutters',
  'Raised among the fighting dogs of the Lower Ward kennels',
  'Sold by their parents to a cruel master for a handful of silver coins',
  'Survived the great plague only to be thrown into the quarantine pits',
  'Found abandoned at the rusted iron gates of the Cinder-Ash Orphanage',
  'Raised by the brutal wardens of the Hollow Hill Foundling House',
  'Survived the silent starvation of the Weeping Sisters',
  'Sold into indentured servitude from the Blackbriar Workhouse at age four',
  'Escaped the disease-ridden dormitories of the Lower Sump Orphanage',
  'Raised in the soot-choked halls of the Iron Orphanage',
  'Survived the brutal winters of the Weeping Stone Foundling Home',
  'Cast out from the Ashen Sisters Charity House for uncontrollable violence',
  'Endured the starvation diets of the Hollow Creek Workhouse',
  'Grew up fighting for scraps in the sunken ruins of the Drowned Ward Orphanage',
  'Abandoned at the rusted gates of the Cinder-Block Orphanage',
  'Survived the chilling cullings of the Weeping Sisters Asylum',
  'Raised amidst the deafening roar of the Ironclad Foundling Home',
  'Sold by desperate parents to the pit-masters of the Whispering Ward',
  'Raised in the soot-choked rafters of the Iron-Gale Foundry',
  'Abandoned to the ravenous tide-pools of the Sunken Ward',
  'Found clutching a silver coin in the ash-drifts of the Pyre District',
  'Survived the relentless floggings of the Black-Briar Orphanage',
  'Sold to a traveling blood-circus before they could even walk',
  'Abandoned on the steps of the Black Iron Orphanage',
  'Survived the great fire of the Ash Quarter Orphanage',
  'Found wandering the crypts below the arena at age four',
  'Raised by the blind monks of the Lantern Hall',
  'Sold to the fighting pits before they could walk',
  'Abandoned at the foot of the Obsidian Obelisk during a blood moon',
  'Raised in the forgotten catacombs beneath the Silent Monastery',
  'Sold for a handful of copper coins to the pit-masters of the Sump',
  'Born in the ash-choked gutters of the Smelting Ward, where children learned to breathe smoke before air',
  'Abandoned at the gates of the Silent Order, raised by monks who only spoke in the language of bruises',
  'Hatched from a lineage of disgraced duelists, carrying a rusted family sword and a ledger of grudges',
  'Surviving the plague-quarantines by scavenging the corpses of the fallen for copper and stale bread',
  "Raised in a traveling freak show, displayed as a monster until they realized the bars couldn't hold them.",
  'Found wailing in a blood-soaked alleyway, with no memory of the massacre that left them an orphan',
  'Sold into the sulfur mines at age six, trading the light of the sun for a pickaxe and a hardened spine',
  'Survived the cruel discipline and starvation of the Iron Spire Orphanage',
  'Sold to pit-fighters by indebted parents for a handful of copper coins',
  'Discovered starving in the forgotten plague wards of the Drowned Ward',
  'Raised in the ash-choked chimneys of the Upper Spire',
  'Left for dead in the gutters of the Alchemist District',
  'Sold to the fighting pits by debt-collectors at age seven',
  'Raised by feral street-dogs in the shadows of the Colosseum',
  'Born in the sunless depths of the Salt Mines',
  'Raised in the soot-stained rafters of the Blackwood Orphanage',
  'Abandoned near the whispering gargoyles of the High Basilica',
  'Found clutching a broken gear in the lower wards of the Clockwork District',
  'Survived the plague-ships anchored in the forgotten harbor',
  'Torn from the brutal training yards of the Sump Guild',
  'Left screaming at the soot-stained doors of the Cinderhouse Orphanage',
  'Found shivering beneath the rusted gratings of the Undercity vents',
  'Raised by a ruthless cabal of pit-fighters in the Black Sun district',
  'Abandoned during the chaotic riots of the Lower Wards',
  'Survived the brutal winter culling in the Frost-touched Slums',
  'Abandoned in the pitch-black oubliettes of the Silent Keep',
  'Found shivering amongst the bones in the Kingswood Ossuary',
  'Traded to the flesh-peddlers of the Red Lantern District for a vial of dream-dust',
  'Survived the great culling of the Hollow Wards by hiding inside a hollowed-out gargoyle',
  'Raised by the blind seers of the Whispering Sands',
  'Abandoned at the blood-stained altars of the Crimson Brotherhood',
  'Abandoned in the smog-choked alleys of the Lower Wards and raised by stray hounds',
  'Born in the sunless depths of the Undercity, fighting for scraps of mouldy bread',
  'Left on the blood-stained steps of the fighting pits as a mere infant',
  "Raised in the lightless oubliettes beneath the High Lord's estate",
  'Forged in the merciless fires of the Cinder-Ash Orphanage',
  'Born in the shadow of the Obsidian Spire to a family of soot-gatherers',
  'Abandoned on the steps of the Silent Sisters with nothing but a rusted pendant',
  'Raised among the feral street urchins of the Sunken Market',
  'Found floating in a wicker basket down the blood-red waters of the Crimson River',
  'Brought up in the gladiatorial slave pens of the Iron Barons',
  'Raised in the suffocating silence of the Iron-Grip Foundling Home',
  'Survived the starvation-lotteries of the Weeping Mother Orphanage',
  'Found swaddled in discarded bandages behind the Bleeding Heart Asylum',
  'Sold to the fighting pits to clear the debts of the Black-Stone Orphanage',
  'Endured the daily beatings of the Matrons of the Hollow Hand',
  'Found shivering among the desecrated tombs of the Howling Crypts',
  'Sold by starving parents to the cruel skin-merchants of the Pale Wards',
  'Raised in the lightless oubliettes of the Black Iron Workhouse',
  'Survived the merciless frostbite cullings of the Weeping Stone Slums',
  'Abandoned to the feral tide pools of the Drowned Quarter',
  'Found half-frozen among the forgotten catacombs beneath the Iron Spire',
  'Raised in the shadow of the gallows at the center of the Weeping Square',
  'Sold for a handful of silver to the merciless flesh-peddlers of the Lower Wards',
  'Survived the terrifying silence of the Black-Briar isolation wards',
  'Abandoned to the feral dog packs that roam the Ash Quarter',
  'Abandoned at the heavy iron gates of the Cinderstone Orphanage',
  'Survived the chilling darkness of the Weeping Vaults',
  'Raised amidst the deafening roar of the Ember Forges',
  'Found swaddled in soot-stained banners beneath the Shattered Bridge',
  'Sold by debt-ridden parents to the cruel pit-masters of the Sump',
  'Raised in the submerged basements of the Drowned Wards',
  'Found clutching a rusted medallion in the alleys of the Ash Quarter',
  'Found adrift in a pitch-black coracle on the Sunless Sea',
  'Raised in the lightless catacombs of the Silent Gods',
  'Discarded in the bone-pits of the Howling Wastes',
  'Raised by the grim executioners of the Iron Tower',
  'Discovered clutching a shattered skull in the deep mines',
  'Surviving the Long Winter by eating rats in the Under-Vault',
  'Abandoned in the rusted iron cages of the Cinder-Ash Orphanage',
  'Raised by the grim grave-keepers of the Obsidian Cemetery',
  'Survived the silent starvation of the Weeping Sisters Asylum',
  'Found swaddled in blood-stained rags beneath the Shattered Bridge',
  'Sold to the pit-masters of the Scab District for a handful of copper',
];
