/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as RunRoundRouteImport } from './routes/run-round'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldIndexRouteImport } from './routes/world/index'
import { Route as StableIndexRouteImport } from './routes/stable/index'
import { Route as LegacyIndexRouteImport } from './routes/legacy/index'
import { Route as WorldTournamentsRouteImport } from './routes/world/tournaments'
import { Route as WorldScoutingRouteImport } from './routes/world/scouting'
import { Route as WorldHistoryRouteImport } from './routes/world/history'
import { Route as WorldGazetteRouteImport } from './routes/world/gazette'
import { Route as WarriorIdRouteImport } from './routes/warrior/$id'
import { Route as StableTrainingRouteImport } from './routes/stable/training'
import { Route as StableTrainersRouteImport } from './routes/stable/trainers'
import { Route as StableRecruitRouteImport } from './routes/stable/recruit'
import { Route as StablePlannerRouteImport } from './routes/stable/planner'
import { Route as StableFinanceRouteImport } from './routes/stable/finance'
import { Route as StableEquipmentRouteImport } from './routes/stable/equipment'
import { Route as StableContractsRouteImport } from './routes/stable/contracts'
import { Route as StableIdRouteImport } from './routes/stable/$id'
import { Route as LegacyTournamentAwardsRouteImport } from './routes/legacy/tournament-awards'
import { Route as LegacyHallOfFameRouteImport } from './routes/legacy/hall-of-fame'
import { Route as LegacyAwardsRouteImport } from './routes/legacy/awards'
import { Route as LegacyAnalyticsRouteImport } from './routes/legacy/analytics'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRoundRoute = RunRoundRouteImport.update({
  id: '/run-round',
  path: '/run-round',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldIndexRoute = WorldIndexRouteImport.update({
  id: '/world/',
  path: '/world/',
  getParentRoute: () => rootRouteImport,
} as any)
const StableIndexRoute = StableIndexRouteImport.update({
  id: '/stable/',
  path: '/stable/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyIndexRoute = LegacyIndexRouteImport.update({
  id: '/legacy/',
  path: '/legacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldTournamentsRoute = WorldTournamentsRouteImport.update({
  id: '/world/tournaments',
  path: '/world/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldScoutingRoute = WorldScoutingRouteImport.update({
  id: '/world/scouting',
  path: '/world/scouting',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldHistoryRoute = WorldHistoryRouteImport.update({
  id: '/world/history',
  path: '/world/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldGazetteRoute = WorldGazetteRouteImport.update({
  id: '/world/gazette',
  path: '/world/gazette',
  getParentRoute: () => rootRouteImport,
} as any)
const WarriorIdRoute = WarriorIdRouteImport.update({
  id: '/warrior/$id',
  path: '/warrior/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StableTrainingRoute = StableTrainingRouteImport.update({
  id: '/stable/training',
  path: '/stable/training',
  getParentRoute: () => rootRouteImport,
} as any)
const StableTrainersRoute = StableTrainersRouteImport.update({
  id: '/stable/trainers',
  path: '/stable/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const StableRecruitRoute = StableRecruitRouteImport.update({
  id: '/stable/recruit',
  path: '/stable/recruit',
  getParentRoute: () => rootRouteImport,
} as any)
const StablePlannerRoute = StablePlannerRouteImport.update({
  id: '/stable/planner',
  path: '/stable/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const StableFinanceRoute = StableFinanceRouteImport.update({
  id: '/stable/finance',
  path: '/stable/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const StableEquipmentRoute = StableEquipmentRouteImport.update({
  id: '/stable/equipment',
  path: '/stable/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const StableContractsRoute = StableContractsRouteImport.update({
  id: '/stable/contracts',
  path: '/stable/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const StableIdRoute = StableIdRouteImport.update({
  id: '/stable/$id',
  path: '/stable/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyTournamentAwardsRoute = LegacyTournamentAwardsRouteImport.update({
  id: '/legacy/tournament-awards',
  path: '/legacy/tournament-awards',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyHallOfFameRoute = LegacyHallOfFameRouteImport.update({
  id: '/legacy/hall-of-fame',
  path: '/legacy/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyAwardsRoute = LegacyAwardsRouteImport.update({
  id: '/legacy/awards',
  path: '/legacy/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyAnalyticsRoute = LegacyAnalyticsRouteImport.update({
  id: '/legacy/analytics',
  path: '/legacy/analytics',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/run-round': typeof RunRoundRoute
  '/welcome': typeof WelcomeRoute
  '/legacy/analytics': typeof LegacyAnalyticsRoute
  '/legacy/awards': typeof LegacyAwardsRoute
  '/legacy/hall-of-fame': typeof LegacyHallOfFameRoute
  '/legacy/tournament-awards': typeof LegacyTournamentAwardsRoute
  '/stable/$id': typeof StableIdRoute
  '/stable/contracts': typeof StableContractsRoute
  '/stable/equipment': typeof StableEquipmentRoute
  '/stable/finance': typeof StableFinanceRoute
  '/stable/planner': typeof StablePlannerRoute
  '/stable/recruit': typeof StableRecruitRoute
  '/stable/trainers': typeof StableTrainersRoute
  '/stable/training': typeof StableTrainingRoute
  '/warrior/$id': typeof WarriorIdRoute
  '/world/gazette': typeof WorldGazetteRoute
  '/world/history': typeof WorldHistoryRoute
  '/world/scouting': typeof WorldScoutingRoute
  '/world/tournaments': typeof WorldTournamentsRoute
  '/legacy/': typeof LegacyIndexRoute
  '/stable/': typeof StableIndexRoute
  '/world/': typeof WorldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/run-round': typeof RunRoundRoute
  '/welcome': typeof WelcomeRoute
  '/legacy/analytics': typeof LegacyAnalyticsRoute
  '/legacy/awards': typeof LegacyAwardsRoute
  '/legacy/hall-of-fame': typeof LegacyHallOfFameRoute
  '/legacy/tournament-awards': typeof LegacyTournamentAwardsRoute
  '/stable/$id': typeof StableIdRoute
  '/stable/contracts': typeof StableContractsRoute
  '/stable/equipment': typeof StableEquipmentRoute
  '/stable/finance': typeof StableFinanceRoute
  '/stable/planner': typeof StablePlannerRoute
  '/stable/recruit': typeof StableRecruitRoute
  '/stable/trainers': typeof StableTrainersRoute
  '/stable/training': typeof StableTrainingRoute
  '/warrior/$id': typeof WarriorIdRoute
  '/world/gazette': typeof WorldGazetteRoute
  '/world/history': typeof WorldHistoryRoute
  '/world/scouting': typeof WorldScoutingRoute
  '/world/tournaments': typeof WorldTournamentsRoute
  '/legacy': typeof LegacyIndexRoute
  '/stable': typeof StableIndexRoute
  '/world': typeof WorldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/help': typeof HelpRoute
  '/run-round': typeof RunRoundRoute
  '/welcome': typeof WelcomeRoute
  '/legacy/analytics': typeof LegacyAnalyticsRoute
  '/legacy/awards': typeof LegacyAwardsRoute
  '/legacy/hall-of-fame': typeof LegacyHallOfFameRoute
  '/legacy/tournament-awards': typeof LegacyTournamentAwardsRoute
  '/stable/$id': typeof StableIdRoute
  '/stable/contracts': typeof StableContractsRoute
  '/stable/equipment': typeof StableEquipmentRoute
  '/stable/finance': typeof StableFinanceRoute
  '/stable/planner': typeof StablePlannerRoute
  '/stable/recruit': typeof StableRecruitRoute
  '/stable/trainers': typeof StableTrainersRoute
  '/stable/training': typeof StableTrainingRoute
  '/warrior/$id': typeof WarriorIdRoute
  '/world/gazette': typeof WorldGazetteRoute
  '/world/history': typeof WorldHistoryRoute
  '/world/scouting': typeof WorldScoutingRoute
  '/world/tournaments': typeof WorldTournamentsRoute
  '/legacy/': typeof LegacyIndexRoute
  '/stable/': typeof StableIndexRoute
  '/world/': typeof WorldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/help'
    | '/run-round'
    | '/welcome'
    | '/legacy/analytics'
    | '/legacy/awards'
    | '/legacy/hall-of-fame'
    | '/legacy/tournament-awards'
    | '/stable/$id'
    | '/stable/contracts'
    | '/stable/equipment'
    | '/stable/finance'
    | '/stable/planner'
    | '/stable/recruit'
    | '/stable/trainers'
    | '/stable/training'
    | '/warrior/$id'
    | '/world/gazette'
    | '/world/history'
    | '/world/scouting'
    | '/world/tournaments'
    | '/legacy/'
    | '/stable/'
    | '/world/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/help'
    | '/run-round'
    | '/welcome'
    | '/legacy/analytics'
    | '/legacy/awards'
    | '/legacy/hall-of-fame'
    | '/legacy/tournament-awards'
    | '/stable/$id'
    | '/stable/contracts'
    | '/stable/equipment'
    | '/stable/finance'
    | '/stable/planner'
    | '/stable/recruit'
    | '/stable/trainers'
    | '/stable/training'
    | '/warrior/$id'
    | '/world/gazette'
    | '/world/history'
    | '/world/scouting'
    | '/world/tournaments'
    | '/legacy'
    | '/stable'
    | '/world'
  id:
    | '__root__'
    | '/'
    | '/help'
    | '/run-round'
    | '/welcome'
    | '/legacy/analytics'
    | '/legacy/awards'
    | '/legacy/hall-of-fame'
    | '/legacy/tournament-awards'
    | '/stable/$id'
    | '/stable/contracts'
    | '/stable/equipment'
    | '/stable/finance'
    | '/stable/planner'
    | '/stable/recruit'
    | '/stable/trainers'
    | '/stable/training'
    | '/warrior/$id'
    | '/world/gazette'
    | '/world/history'
    | '/world/scouting'
    | '/world/tournaments'
    | '/legacy/'
    | '/stable/'
    | '/world/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HelpRoute: typeof HelpRoute
  RunRoundRoute: typeof RunRoundRoute
  WelcomeRoute: typeof WelcomeRoute
  LegacyAnalyticsRoute: typeof LegacyAnalyticsRoute
  LegacyAwardsRoute: typeof LegacyAwardsRoute
  LegacyHallOfFameRoute: typeof LegacyHallOfFameRoute
  LegacyTournamentAwardsRoute: typeof LegacyTournamentAwardsRoute
  StableIdRoute: typeof StableIdRoute
  StableContractsRoute: typeof StableContractsRoute
  StableEquipmentRoute: typeof StableEquipmentRoute
  StableFinanceRoute: typeof StableFinanceRoute
  StablePlannerRoute: typeof StablePlannerRoute
  StableRecruitRoute: typeof StableRecruitRoute
  StableTrainersRoute: typeof StableTrainersRoute
  StableTrainingRoute: typeof StableTrainingRoute
  WarriorIdRoute: typeof WarriorIdRoute
  WorldGazetteRoute: typeof WorldGazetteRoute
  WorldHistoryRoute: typeof WorldHistoryRoute
  WorldScoutingRoute: typeof WorldScoutingRoute
  WorldTournamentsRoute: typeof WorldTournamentsRoute
  LegacyIndexRoute: typeof LegacyIndexRoute
  StableIndexRoute: typeof StableIndexRoute
  WorldIndexRoute: typeof WorldIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run-round': {
      id: '/run-round'
      path: '/run-round'
      fullPath: '/run-round'
      preLoaderRoute: typeof RunRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/': {
      id: '/world/'
      path: '/world'
      fullPath: '/world/'
      preLoaderRoute: typeof WorldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/': {
      id: '/stable/'
      path: '/stable'
      fullPath: '/stable/'
      preLoaderRoute: typeof StableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/': {
      id: '/legacy/'
      path: '/legacy'
      fullPath: '/legacy/'
      preLoaderRoute: typeof LegacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/tournaments': {
      id: '/world/tournaments'
      path: '/world/tournaments'
      fullPath: '/world/tournaments'
      preLoaderRoute: typeof WorldTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/scouting': {
      id: '/world/scouting'
      path: '/world/scouting'
      fullPath: '/world/scouting'
      preLoaderRoute: typeof WorldScoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/history': {
      id: '/world/history'
      path: '/world/history'
      fullPath: '/world/history'
      preLoaderRoute: typeof WorldHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/gazette': {
      id: '/world/gazette'
      path: '/world/gazette'
      fullPath: '/world/gazette'
      preLoaderRoute: typeof WorldGazetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warrior/$id': {
      id: '/warrior/$id'
      path: '/warrior/$id'
      fullPath: '/warrior/$id'
      preLoaderRoute: typeof WarriorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/training': {
      id: '/stable/training'
      path: '/stable/training'
      fullPath: '/stable/training'
      preLoaderRoute: typeof StableTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/trainers': {
      id: '/stable/trainers'
      path: '/stable/trainers'
      fullPath: '/stable/trainers'
      preLoaderRoute: typeof StableTrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/recruit': {
      id: '/stable/recruit'
      path: '/stable/recruit'
      fullPath: '/stable/recruit'
      preLoaderRoute: typeof StableRecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/planner': {
      id: '/stable/planner'
      path: '/stable/planner'
      fullPath: '/stable/planner'
      preLoaderRoute: typeof StablePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/finance': {
      id: '/stable/finance'
      path: '/stable/finance'
      fullPath: '/stable/finance'
      preLoaderRoute: typeof StableFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/equipment': {
      id: '/stable/equipment'
      path: '/stable/equipment'
      fullPath: '/stable/equipment'
      preLoaderRoute: typeof StableEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/contracts': {
      id: '/stable/contracts'
      path: '/stable/contracts'
      fullPath: '/stable/contracts'
      preLoaderRoute: typeof StableContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/$id': {
      id: '/stable/$id'
      path: '/stable/$id'
      fullPath: '/stable/$id'
      preLoaderRoute: typeof StableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/tournament-awards': {
      id: '/legacy/tournament-awards'
      path: '/legacy/tournament-awards'
      fullPath: '/legacy/tournament-awards'
      preLoaderRoute: typeof LegacyTournamentAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/hall-of-fame': {
      id: '/legacy/hall-of-fame'
      path: '/legacy/hall-of-fame'
      fullPath: '/legacy/hall-of-fame'
      preLoaderRoute: typeof LegacyHallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/awards': {
      id: '/legacy/awards'
      path: '/legacy/awards'
      fullPath: '/legacy/awards'
      preLoaderRoute: typeof LegacyAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy/analytics': {
      id: '/legacy/analytics'
      path: '/legacy/analytics'
      fullPath: '/legacy/analytics'
      preLoaderRoute: typeof LegacyAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HelpRoute: HelpRoute,
  RunRoundRoute: RunRoundRoute,
  WelcomeRoute: WelcomeRoute,
  LegacyAnalyticsRoute: LegacyAnalyticsRoute,
  LegacyAwardsRoute: LegacyAwardsRoute,
  LegacyHallOfFameRoute: LegacyHallOfFameRoute,
  LegacyTournamentAwardsRoute: LegacyTournamentAwardsRoute,
  StableIdRoute: StableIdRoute,
  StableContractsRoute: StableContractsRoute,
  StableEquipmentRoute: StableEquipmentRoute,
  StableFinanceRoute: StableFinanceRoute,
  StablePlannerRoute: StablePlannerRoute,
  StableRecruitRoute: StableRecruitRoute,
  StableTrainersRoute: StableTrainersRoute,
  StableTrainingRoute: StableTrainingRoute,
  WarriorIdRoute: WarriorIdRoute,
  WorldGazetteRoute: WorldGazetteRoute,
  WorldHistoryRoute: WorldHistoryRoute,
  WorldScoutingRoute: WorldScoutingRoute,
  WorldTournamentsRoute: WorldTournamentsRoute,
  LegacyIndexRoute: LegacyIndexRoute,
  StableIndexRoute: StableIndexRoute,
  WorldIndexRoute: WorldIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
