/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as World_rootRouteImport } from './routes/world/__root'
import { Route as Stable_rootRouteImport } from './routes/stable/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as HelpRouteImport } from './routes/help'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as ArenaHubRouteImport } from './routes/arena-hub'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorldIndexRouteImport } from './routes/world/index'
import { Route as StableIndexRouteImport } from './routes/stable/index'
import { Route as WorldTournamentsRouteImport } from './routes/world/tournaments'
import { Route as WorldScoutingRouteImport } from './routes/world/scouting'
import { Route as WorldHistoryRouteImport } from './routes/world/history'
import { Route as WorldGraveyardRouteImport } from './routes/world/graveyard'
import { Route as WorldChronicleRouteImport } from './routes/world/chronicle'
import { Route as WorldArenaLeaderboardsRouteImport } from './routes/world/arena-leaderboards'
import { Route as WarriorIdRouteImport } from './routes/warrior/$id'
import { Route as ToolsPhysicalsSimulatorRouteImport } from './routes/tools/physicals-simulator'
import { Route as StableTrainingRouteImport } from './routes/stable/training'
import { Route as StableTrainersRouteImport } from './routes/stable/trainers'
import { Route as StableRosterRouteImport } from './routes/stable/roster'
import { Route as StableRecruitRouteImport } from './routes/stable/recruit'
import { Route as StablePromotersRouteImport } from './routes/stable/promoters'
import { Route as StablePlannerRouteImport } from './routes/stable/planner'
import { Route as StableOffseasonRouteImport } from './routes/stable/offseason'
import { Route as StableFinanceRouteImport } from './routes/stable/finance'
import { Route as StableEquipmentRouteImport } from './routes/stable/equipment'
import { Route as StableBoutsRouteImport } from './routes/stable/bouts'
import { Route as StableArenaRouteImport } from './routes/stable/arena'
import { Route as LoreHallOfFightsRouteImport } from './routes/lore/hall-of-fights'
import { Route as WorldStableIdRouteImport } from './routes/world/stable/$id'
import { Route as StablePromoterIdRouteImport } from './routes/stable/promoter.$id'

const World_rootRoute = World_rootRouteImport.update({
  id: '/world/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const Stable_rootRoute = Stable_rootRouteImport.update({
  id: '/stable/__root',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaHubRoute = ArenaHubRouteImport.update({
  id: '/arena-hub',
  path: '/arena-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldIndexRoute = WorldIndexRouteImport.update({
  id: '/world/',
  path: '/world/',
  getParentRoute: () => rootRouteImport,
} as any)
const StableIndexRoute = StableIndexRouteImport.update({
  id: '/stable/',
  path: '/stable/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldTournamentsRoute = WorldTournamentsRouteImport.update({
  id: '/world/tournaments',
  path: '/world/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldScoutingRoute = WorldScoutingRouteImport.update({
  id: '/world/scouting',
  path: '/world/scouting',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldHistoryRoute = WorldHistoryRouteImport.update({
  id: '/world/history',
  path: '/world/history',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldGraveyardRoute = WorldGraveyardRouteImport.update({
  id: '/world/graveyard',
  path: '/world/graveyard',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldChronicleRoute = WorldChronicleRouteImport.update({
  id: '/world/chronicle',
  path: '/world/chronicle',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldArenaLeaderboardsRoute = WorldArenaLeaderboardsRouteImport.update({
  id: '/world/arena-leaderboards',
  path: '/world/arena-leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const WarriorIdRoute = WarriorIdRouteImport.update({
  id: '/warrior/$id',
  path: '/warrior/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsPhysicalsSimulatorRoute = ToolsPhysicalsSimulatorRouteImport.update({
  id: '/tools/physicals-simulator',
  path: '/tools/physicals-simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const StableTrainingRoute = StableTrainingRouteImport.update({
  id: '/stable/training',
  path: '/stable/training',
  getParentRoute: () => rootRouteImport,
} as any)
const StableTrainersRoute = StableTrainersRouteImport.update({
  id: '/stable/trainers',
  path: '/stable/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const StableRosterRoute = StableRosterRouteImport.update({
  id: '/stable/roster',
  path: '/stable/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const StableRecruitRoute = StableRecruitRouteImport.update({
  id: '/stable/recruit',
  path: '/stable/recruit',
  getParentRoute: () => rootRouteImport,
} as any)
const StablePromotersRoute = StablePromotersRouteImport.update({
  id: '/stable/promoters',
  path: '/stable/promoters',
  getParentRoute: () => rootRouteImport,
} as any)
const StablePlannerRoute = StablePlannerRouteImport.update({
  id: '/stable/planner',
  path: '/stable/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const StableOffseasonRoute = StableOffseasonRouteImport.update({
  id: '/stable/offseason',
  path: '/stable/offseason',
  getParentRoute: () => rootRouteImport,
} as any)
const StableFinanceRoute = StableFinanceRouteImport.update({
  id: '/stable/finance',
  path: '/stable/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const StableEquipmentRoute = StableEquipmentRouteImport.update({
  id: '/stable/equipment',
  path: '/stable/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const StableBoutsRoute = StableBoutsRouteImport.update({
  id: '/stable/bouts',
  path: '/stable/bouts',
  getParentRoute: () => rootRouteImport,
} as any)
const StableArenaRoute = StableArenaRouteImport.update({
  id: '/stable/arena',
  path: '/stable/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const LoreHallOfFightsRoute = LoreHallOfFightsRouteImport.update({
  id: '/lore/hall-of-fights',
  path: '/lore/hall-of-fights',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldStableIdRoute = WorldStableIdRouteImport.update({
  id: '/world/stable/$id',
  path: '/world/stable/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StablePromoterIdRoute = StablePromoterIdRouteImport.update({
  id: '/stable/promoter/$id',
  path: '/stable/promoter/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena-hub': typeof ArenaHubRoute
  '/bookmarks': typeof BookmarksRoute
  '/help': typeof HelpRoute
  '/welcome': typeof WelcomeRoute
  '/lore/hall-of-fights': typeof LoreHallOfFightsRoute
  '/stable': typeof Stable_rootRoute
  '/stable/arena': typeof StableArenaRoute
  '/stable/bouts': typeof StableBoutsRoute
  '/stable/equipment': typeof StableEquipmentRoute
  '/stable/finance': typeof StableFinanceRoute
  '/stable/offseason': typeof StableOffseasonRoute
  '/stable/planner': typeof StablePlannerRoute
  '/stable/promoters': typeof StablePromotersRoute
  '/stable/recruit': typeof StableRecruitRoute
  '/stable/roster': typeof StableRosterRoute
  '/stable/trainers': typeof StableTrainersRoute
  '/stable/training': typeof StableTrainingRoute
  '/tools/physicals-simulator': typeof ToolsPhysicalsSimulatorRoute
  '/warrior/$id': typeof WarriorIdRoute
  '/world': typeof World_rootRoute
  '/world/arena-leaderboards': typeof WorldArenaLeaderboardsRoute
  '/world/chronicle': typeof WorldChronicleRoute
  '/world/graveyard': typeof WorldGraveyardRoute
  '/world/history': typeof WorldHistoryRoute
  '/world/scouting': typeof WorldScoutingRoute
  '/world/tournaments': typeof WorldTournamentsRoute
  '/stable/': typeof StableIndexRoute
  '/world/': typeof WorldIndexRoute
  '/stable/promoter/$id': typeof StablePromoterIdRoute
  '/world/stable/$id': typeof WorldStableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena-hub': typeof ArenaHubRoute
  '/bookmarks': typeof BookmarksRoute
  '/help': typeof HelpRoute
  '/welcome': typeof WelcomeRoute
  '/lore/hall-of-fights': typeof LoreHallOfFightsRoute
  '/stable': typeof StableIndexRoute
  '/stable/arena': typeof StableArenaRoute
  '/stable/bouts': typeof StableBoutsRoute
  '/stable/equipment': typeof StableEquipmentRoute
  '/stable/finance': typeof StableFinanceRoute
  '/stable/offseason': typeof StableOffseasonRoute
  '/stable/planner': typeof StablePlannerRoute
  '/stable/promoters': typeof StablePromotersRoute
  '/stable/recruit': typeof StableRecruitRoute
  '/stable/roster': typeof StableRosterRoute
  '/stable/trainers': typeof StableTrainersRoute
  '/stable/training': typeof StableTrainingRoute
  '/tools/physicals-simulator': typeof ToolsPhysicalsSimulatorRoute
  '/warrior/$id': typeof WarriorIdRoute
  '/world': typeof WorldIndexRoute
  '/world/arena-leaderboards': typeof WorldArenaLeaderboardsRoute
  '/world/chronicle': typeof WorldChronicleRoute
  '/world/graveyard': typeof WorldGraveyardRoute
  '/world/history': typeof WorldHistoryRoute
  '/world/scouting': typeof WorldScoutingRoute
  '/world/tournaments': typeof WorldTournamentsRoute
  '/stable/promoter/$id': typeof StablePromoterIdRoute
  '/world/stable/$id': typeof WorldStableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arena-hub': typeof ArenaHubRoute
  '/bookmarks': typeof BookmarksRoute
  '/help': typeof HelpRoute
  '/welcome': typeof WelcomeRoute
  '/lore/hall-of-fights': typeof LoreHallOfFightsRoute
  '/stable/__root': typeof Stable_rootRoute
  '/stable/arena': typeof StableArenaRoute
  '/stable/bouts': typeof StableBoutsRoute
  '/stable/equipment': typeof StableEquipmentRoute
  '/stable/finance': typeof StableFinanceRoute
  '/stable/offseason': typeof StableOffseasonRoute
  '/stable/planner': typeof StablePlannerRoute
  '/stable/promoters': typeof StablePromotersRoute
  '/stable/recruit': typeof StableRecruitRoute
  '/stable/roster': typeof StableRosterRoute
  '/stable/trainers': typeof StableTrainersRoute
  '/stable/training': typeof StableTrainingRoute
  '/tools/physicals-simulator': typeof ToolsPhysicalsSimulatorRoute
  '/warrior/$id': typeof WarriorIdRoute
  '/world/__root': typeof World_rootRoute
  '/world/arena-leaderboards': typeof WorldArenaLeaderboardsRoute
  '/world/chronicle': typeof WorldChronicleRoute
  '/world/graveyard': typeof WorldGraveyardRoute
  '/world/history': typeof WorldHistoryRoute
  '/world/scouting': typeof WorldScoutingRoute
  '/world/tournaments': typeof WorldTournamentsRoute
  '/stable/': typeof StableIndexRoute
  '/world/': typeof WorldIndexRoute
  '/stable/promoter/$id': typeof StablePromoterIdRoute
  '/world/stable/$id': typeof WorldStableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arena-hub'
    | '/bookmarks'
    | '/help'
    | '/welcome'
    | '/lore/hall-of-fights'
    | '/stable'
    | '/stable/arena'
    | '/stable/bouts'
    | '/stable/equipment'
    | '/stable/finance'
    | '/stable/offseason'
    | '/stable/planner'
    | '/stable/promoters'
    | '/stable/recruit'
    | '/stable/roster'
    | '/stable/trainers'
    | '/stable/training'
    | '/tools/physicals-simulator'
    | '/warrior/$id'
    | '/world'
    | '/world/arena-leaderboards'
    | '/world/chronicle'
    | '/world/graveyard'
    | '/world/history'
    | '/world/scouting'
    | '/world/tournaments'
    | '/stable/'
    | '/world/'
    | '/stable/promoter/$id'
    | '/world/stable/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arena-hub'
    | '/bookmarks'
    | '/help'
    | '/welcome'
    | '/lore/hall-of-fights'
    | '/stable'
    | '/stable/arena'
    | '/stable/bouts'
    | '/stable/equipment'
    | '/stable/finance'
    | '/stable/offseason'
    | '/stable/planner'
    | '/stable/promoters'
    | '/stable/recruit'
    | '/stable/roster'
    | '/stable/trainers'
    | '/stable/training'
    | '/tools/physicals-simulator'
    | '/warrior/$id'
    | '/world'
    | '/world/arena-leaderboards'
    | '/world/chronicle'
    | '/world/graveyard'
    | '/world/history'
    | '/world/scouting'
    | '/world/tournaments'
    | '/stable/promoter/$id'
    | '/world/stable/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arena-hub'
    | '/bookmarks'
    | '/help'
    | '/welcome'
    | '/lore/hall-of-fights'
    | '/stable/__root'
    | '/stable/arena'
    | '/stable/bouts'
    | '/stable/equipment'
    | '/stable/finance'
    | '/stable/offseason'
    | '/stable/planner'
    | '/stable/promoters'
    | '/stable/recruit'
    | '/stable/roster'
    | '/stable/trainers'
    | '/stable/training'
    | '/tools/physicals-simulator'
    | '/warrior/$id'
    | '/world/__root'
    | '/world/arena-leaderboards'
    | '/world/chronicle'
    | '/world/graveyard'
    | '/world/history'
    | '/world/scouting'
    | '/world/tournaments'
    | '/stable/'
    | '/world/'
    | '/stable/promoter/$id'
    | '/world/stable/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArenaHubRoute: typeof ArenaHubRoute
  BookmarksRoute: typeof BookmarksRoute
  HelpRoute: typeof HelpRoute
  WelcomeRoute: typeof WelcomeRoute
  LoreHallOfFightsRoute: typeof LoreHallOfFightsRoute
  Stable_rootRoute: typeof Stable_rootRoute
  StableArenaRoute: typeof StableArenaRoute
  StableBoutsRoute: typeof StableBoutsRoute
  StableEquipmentRoute: typeof StableEquipmentRoute
  StableFinanceRoute: typeof StableFinanceRoute
  StableOffseasonRoute: typeof StableOffseasonRoute
  StablePlannerRoute: typeof StablePlannerRoute
  StablePromotersRoute: typeof StablePromotersRoute
  StableRecruitRoute: typeof StableRecruitRoute
  StableRosterRoute: typeof StableRosterRoute
  StableTrainersRoute: typeof StableTrainersRoute
  StableTrainingRoute: typeof StableTrainingRoute
  ToolsPhysicalsSimulatorRoute: typeof ToolsPhysicalsSimulatorRoute
  WarriorIdRoute: typeof WarriorIdRoute
  World_rootRoute: typeof World_rootRoute
  WorldArenaLeaderboardsRoute: typeof WorldArenaLeaderboardsRoute
  WorldChronicleRoute: typeof WorldChronicleRoute
  WorldGraveyardRoute: typeof WorldGraveyardRoute
  WorldHistoryRoute: typeof WorldHistoryRoute
  WorldScoutingRoute: typeof WorldScoutingRoute
  WorldTournamentsRoute: typeof WorldTournamentsRoute
  StableIndexRoute: typeof StableIndexRoute
  WorldIndexRoute: typeof WorldIndexRoute
  StablePromoterIdRoute: typeof StablePromoterIdRoute
  WorldStableIdRoute: typeof WorldStableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/world/__root': {
      id: '/world/__root'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof World_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/__root': {
      id: '/stable/__root'
      path: '/stable'
      fullPath: '/stable'
      preLoaderRoute: typeof Stable_rootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena-hub': {
      id: '/arena-hub'
      path: '/arena-hub'
      fullPath: '/arena-hub'
      preLoaderRoute: typeof ArenaHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/': {
      id: '/world/'
      path: '/world'
      fullPath: '/world/'
      preLoaderRoute: typeof WorldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/': {
      id: '/stable/'
      path: '/stable'
      fullPath: '/stable/'
      preLoaderRoute: typeof StableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/tournaments': {
      id: '/world/tournaments'
      path: '/world/tournaments'
      fullPath: '/world/tournaments'
      preLoaderRoute: typeof WorldTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/scouting': {
      id: '/world/scouting'
      path: '/world/scouting'
      fullPath: '/world/scouting'
      preLoaderRoute: typeof WorldScoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/history': {
      id: '/world/history'
      path: '/world/history'
      fullPath: '/world/history'
      preLoaderRoute: typeof WorldHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/graveyard': {
      id: '/world/graveyard'
      path: '/world/graveyard'
      fullPath: '/world/graveyard'
      preLoaderRoute: typeof WorldGraveyardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/chronicle': {
      id: '/world/chronicle'
      path: '/world/chronicle'
      fullPath: '/world/chronicle'
      preLoaderRoute: typeof WorldChronicleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/arena-leaderboards': {
      id: '/world/arena-leaderboards'
      path: '/world/arena-leaderboards'
      fullPath: '/world/arena-leaderboards'
      preLoaderRoute: typeof WorldArenaLeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warrior/$id': {
      id: '/warrior/$id'
      path: '/warrior/$id'
      fullPath: '/warrior/$id'
      preLoaderRoute: typeof WarriorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/physicals-simulator': {
      id: '/tools/physicals-simulator'
      path: '/tools/physicals-simulator'
      fullPath: '/tools/physicals-simulator'
      preLoaderRoute: typeof ToolsPhysicalsSimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/training': {
      id: '/stable/training'
      path: '/stable/training'
      fullPath: '/stable/training'
      preLoaderRoute: typeof StableTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/trainers': {
      id: '/stable/trainers'
      path: '/stable/trainers'
      fullPath: '/stable/trainers'
      preLoaderRoute: typeof StableTrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/roster': {
      id: '/stable/roster'
      path: '/stable/roster'
      fullPath: '/stable/roster'
      preLoaderRoute: typeof StableRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/recruit': {
      id: '/stable/recruit'
      path: '/stable/recruit'
      fullPath: '/stable/recruit'
      preLoaderRoute: typeof StableRecruitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/promoters': {
      id: '/stable/promoters'
      path: '/stable/promoters'
      fullPath: '/stable/promoters'
      preLoaderRoute: typeof StablePromotersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/planner': {
      id: '/stable/planner'
      path: '/stable/planner'
      fullPath: '/stable/planner'
      preLoaderRoute: typeof StablePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/offseason': {
      id: '/stable/offseason'
      path: '/stable/offseason'
      fullPath: '/stable/offseason'
      preLoaderRoute: typeof StableOffseasonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/finance': {
      id: '/stable/finance'
      path: '/stable/finance'
      fullPath: '/stable/finance'
      preLoaderRoute: typeof StableFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/equipment': {
      id: '/stable/equipment'
      path: '/stable/equipment'
      fullPath: '/stable/equipment'
      preLoaderRoute: typeof StableEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/bouts': {
      id: '/stable/bouts'
      path: '/stable/bouts'
      fullPath: '/stable/bouts'
      preLoaderRoute: typeof StableBoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/arena': {
      id: '/stable/arena'
      path: '/stable/arena'
      fullPath: '/stable/arena'
      preLoaderRoute: typeof StableArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lore/hall-of-fights': {
      id: '/lore/hall-of-fights'
      path: '/lore/hall-of-fights'
      fullPath: '/lore/hall-of-fights'
      preLoaderRoute: typeof LoreHallOfFightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/stable/$id': {
      id: '/world/stable/$id'
      path: '/world/stable/$id'
      fullPath: '/world/stable/$id'
      preLoaderRoute: typeof WorldStableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stable/promoter/$id': {
      id: '/stable/promoter/$id'
      path: '/stable/promoter/$id'
      fullPath: '/stable/promoter/$id'
      preLoaderRoute: typeof StablePromoterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArenaHubRoute: ArenaHubRoute,
  BookmarksRoute: BookmarksRoute,
  HelpRoute: HelpRoute,
  WelcomeRoute: WelcomeRoute,
  LoreHallOfFightsRoute: LoreHallOfFightsRoute,
  Stable_rootRoute: Stable_rootRoute,
  StableArenaRoute: StableArenaRoute,
  StableBoutsRoute: StableBoutsRoute,
  StableEquipmentRoute: StableEquipmentRoute,
  StableFinanceRoute: StableFinanceRoute,
  StableOffseasonRoute: StableOffseasonRoute,
  StablePlannerRoute: StablePlannerRoute,
  StablePromotersRoute: StablePromotersRoute,
  StableRecruitRoute: StableRecruitRoute,
  StableRosterRoute: StableRosterRoute,
  StableTrainersRoute: StableTrainersRoute,
  StableTrainingRoute: StableTrainingRoute,
  ToolsPhysicalsSimulatorRoute: ToolsPhysicalsSimulatorRoute,
  WarriorIdRoute: WarriorIdRoute,
  World_rootRoute: World_rootRoute,
  WorldArenaLeaderboardsRoute: WorldArenaLeaderboardsRoute,
  WorldChronicleRoute: WorldChronicleRoute,
  WorldGraveyardRoute: WorldGraveyardRoute,
  WorldHistoryRoute: WorldHistoryRoute,
  WorldScoutingRoute: WorldScoutingRoute,
  WorldTournamentsRoute: WorldTournamentsRoute,
  StableIndexRoute: StableIndexRoute,
  WorldIndexRoute: WorldIndexRoute,
  StablePromoterIdRoute: StablePromoterIdRoute,
  WorldStableIdRoute: WorldStableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
